# Reinforcement Learning for Trading Strategies - DQL

### 1.0 Import Libraries

In [8]:
import keras
from keras.models import Sequential
from keras.models import load_model
from keras.layers import Dense
from keras.optimizers import Adam
import math
import numpy as np
import random
from collections import deque

### 2.0 Creating Agent

In [45]:
class Agent:
    def __init__(self,state_size,is_eval=False,model_name=""):
        self.state_size = state_size # normalized previous day
        self.action_size = 3 # sit,buy, sell
        self.memory = deque(maxlen=1000)
        self.inventory = []
        self.model_name = model_name
        self.is_eval = is_eval
        self.gamma = 0.95
        self.epsilon = 1.0
        self.epsilon_decay = 0.995
        self.epsilon_min = 0.01
        self.model = load_model(model_name) if is_eval else self._model()
    def _model(self):
        model = Sequential()
        model.add(Dense(units=64, input_dim=self.state_size, activation="relu"))
        model.add(Dense(units=32, activation="relu"))
        model.add(Dense(units=8, activation="relu"))
        model.add(Dense(self.action_size, activation="linear"))
        model.compile(loss="mse", optimizer=Adam(lr=0.001))
        return model
    def act(self, state):
        if not self.is_eval and random.random()<= self.epsilon:
            return random.randrange(self.action_size)
        options = self.model.predict(state)
        return np.argmax(options[0])
    def expReplay(self, batch_size):
        mini_batch = []
        l = len(self.memory)
        for i in range(l - batch_size + 1, l):
            mini_batch.append(self.memory[i])
        for state, action, reward, next_state, done in mini_batch:
            target = reward
            if not done:
                target = reward + self.gamma * np.amax(self.model.predict(next_state)[0])
            target_f = self.model.predict(state)
            target_f[0][action] = target
            self.model.fit(state, target_f, epochs=1, verbose=0)
        if self.epsilon > self.epsilon_min:
            self.epsilon *= self.epsilon_decay

### 3.0 Define Basic Function

In [46]:
def formatPrice(n):
    return("-Rs." if n<0 else "Rs.")+"{0:.2f}".format(abs(n))
def getStockDataVec(key):
    vec = []
    lines = open(key+".csv","r").read().splitlines()
    for line in lines[1:]:
        #print(line)
        #print(float(line.split(",")[4]))
        vec.append(float(line.split(",")[4]))
        #print(vec)
    return vec 
def sigmoid(x):
    return 1/(1+math.exp(-x))
def getState(data, t, n):
    d = t - n + 1
    block = data[d:t + 1] if d >= 0 else -d * [data[0]] + data[0:t + 1] # pad with t0
    res = []
    for i in range(n - 1):
        res.append(sigmoid(block[i + 1] - block[i]))
    return np.array([res])

In [47]:
t=0
n=10
d = t - n + 1
block = data[d:t + 1] if d >= 0 else -d * [data[0]] + data[0:t + 1] # pad with t0
res = []
for i in range(n - 1):
        res.append(sigmoid(block[i + 1] - block[i]))
print(res)

[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]


### 3.0 Training the Agent

In [48]:
import sys
stock_name = input("Enter stock_name, window_size, Episode_count")
window_size = input()
episode_count = input()
stock_name = str(stock_name)
window_size = int(window_size)
episode_count = int(episode_count)
agent = Agent(window_size)
data = getStockDataVec(stock_name)
l = len(data) - 1
batch_size = 32
for e in range(episode_count + 1):
    print("Episode " + str(e) + "/" + str(episode_count))
    state = getState(data, 0, window_size + 1)
    total_profit = 0
    agent.inventory = []
    for t in range(l):
        action = agent.act(state)
        # sit
        next_state = getState(data, t + 1, window_size + 1)
        reward = 0
        if action == 1: # buy
            agent.inventory.append(data[t])
            print("Buy: " + formatPrice(data[t]))
        elif action == 2 and len(agent.inventory) > 0: # sell
            bought_price = window_size_price = agent.inventory.pop(0)
            reward = max(data[t] - bought_price, 0)
            total_profit += data[t] - bought_price
            print("Sell: " + formatPrice(data[t]) + " | Profit: " + formatPrice(data[t] - bought_price))
        done = True if t == l - 1 else False
        agent.memory.append((state, action, reward, next_state, done))
        state = next_state
        if done:
            print("--------------------------------")
            print("Total Profit: " + formatPrice(total_profit))
            print("--------------------------------")
        if len(agent.memory) > batch_size:
            agent.expReplay(batch_size)
    if e % 10 == 0:
        agent.model.save(str(e))

Enter stock_name, window_size, Episode_count7043.KL
10
1
Episode 0/1
Buy: Rs.0.40
Sell: Rs.0.39 | Profit: -Rs.0.01
Buy: Rs.0.49
Sell: Rs.0.49 | Profit: Rs.0.00
Buy: Rs.0.49
Buy: Rs.0.49
Sell: Rs.0.49 | Profit: Rs.0.00
Sell: Rs.0.49 | Profit: Rs.0.00
Buy: Rs.0.49
Buy: Rs.0.49
Sell: Rs.0.49 | Profit: Rs.0.00
Buy: Rs.0.49
Sell: Rs.0.49 | Profit: Rs.0.00
Buy: Rs.0.49
Sell: Rs.0.49 | Profit: Rs.0.00
Buy: Rs.0.49
Sell: Rs.0.49 | Profit: Rs.0.00
Sell: Rs.0.49 | Profit: Rs.0.00
Buy: Rs.0.49
Buy: Rs.0.49
[[0.24119173 0.11570881 0.20879751]]
2
[[0.29189643 0.15817364 0.26056948]]
2
[[0.34309652 0.20228672 0.31372598]]
0
[[0.35150442 0.22277637 0.3332692 ]]
2
[[0.36190248 0.24191907 0.3526394 ]]
2
[[0.36346844 0.25058267 0.36121756]]
2
[[0.34871137 0.24342854 0.35087058]]
1
[[0.35832354 0.26569757 0.3688389 ]]
0
[[0.3601954  0.27950582 0.37784904]]
0
[[0.35767803 0.2883991  0.38166463]]
0
[[0.35719374 0.30009186 0.3876104 ]]
0
[[0.3668505  0.31459188 0.40011716]]
2
[[0.37410405 0.32579076 0.40942

[[0.02580999 0.02592517 0.02522487]]
0
[[0.02577525 0.0256876  0.02507436]]
1
[[0.02576463 0.02539822 0.02490135]]
0
[[0.02557309 0.02515942 0.02469901]]
2
[[0.02538579 0.02493135 0.02449471]]
1
[[0.02523104 0.02467431 0.02428498]]
2
[[0.02508007 0.02443252 0.02407873]]
1
[[0.02495451 0.02417604 0.02387365]]
2
[[0.02483523 0.02393935 0.02367955]]
1
[[0.02473373 0.02370386 0.02349356]]
2
[[0.02464231 0.02349146 0.02332591]]
2
[[0.02456293 0.0233025  0.02317927]]
0
[[0.02431432 0.02315387 0.02300213]]
1
[[0.02409107 0.02301623 0.02284057]]
1
[[0.02432276 0.02307401 0.02300129]]
0
[[0.02307643 0.02284772 0.02236958]]
0
[[0.02265354 0.02272769 0.02215593]]
2
[[0.02152752 0.02278211 0.02177025]]
0
[[0.02140962 0.02213958 0.02128962]]
1
[[0.02039989 0.02283016 0.02141452]]
1
Buy: Rs.0.42
[[0.02214554 0.02308878 0.02235678]]
0
[[0.02164938 0.02306896 0.02218052]]
0
[[0.02055564 0.02218726 0.02113476]]
0
[[0.01827573 0.02227078 0.02029695]]
0
[[0.01883429 0.02203302 0.02035154]]
2
[[0.02147845

[[0.16042413 0.14356363 0.15942676]]
2
[[0.16180316 0.14593358 0.16217469]]
1
[[0.163826   0.15074988 0.16660361]]
0
[[0.16303687 0.1555073  0.16994806]]
1
[[0.16063079 0.16088594 0.17293622]]
0
[[0.16005155 0.16523644 0.17584662]]
2
[[0.15902197 0.16798426 0.17718992]]
1
[[0.15803312 0.1705621  0.17843746]]
2
[[0.15660259 0.1717698  0.17829998]]
1
[[0.15562306 0.1721983  0.17788579]]
2
[[0.15420963 0.17156827 0.1763301 ]]
1
[[0.15345517 0.16996893 0.17450318]]
2
[[0.15227708 0.16763273 0.17178997]]
2
[[0.15075827 0.16468716 0.16834785]]
0
[[0.1528835  0.16120185 0.16590096]]
1
[[0.15514052 0.15731928 0.16340746]]
1
[[0.15715067 0.15330334 0.16085081]]
0
[[0.15707523 0.15019812 0.15824035]]
0
[[0.15455994 0.14781325 0.15533006]]
2
[[0.15225673 0.14594536 0.15270486]]
0
[[0.14721751 0.14413862 0.14920567]]
1
[[0.14240962 0.14373323 0.14681111]]
1
[[0.13909924 0.14164159 0.14396732]]
1
[[0.13542229 0.14048384 0.1416916 ]]
2
[[0.1324743  0.13813177 0.13873334]]
2
[[0.13222115 0.13823816 0

[[0.19803071 0.19135068 0.20323502]]
2
[[0.19889624 0.19446225 0.20718393]]
2
[[0.19923484 0.19631447 0.20972219]]
2
[[0.19993296 0.19800043 0.21198295]]
0
[[0.2019379  0.19988076 0.21477172]]
1
[[0.20074555 0.2003214  0.21514133]]
0
[[0.20281346 0.20170751 0.21733038]]
2
[[0.2034275  0.20222142 0.21806405]]
1
[[0.20384315 0.2033554  0.21898906]]
2
[[0.20321631 0.20379253 0.21878225]]
1
[[0.2025378  0.20473967 0.21881223]]
2
[[0.2009275  0.2050075  0.21779983]]
1
[[0.19942477 0.20550954 0.21699008]]
2
[[0.19708888 0.20538232 0.21523723]]
2
[[0.19402175 0.20469594 0.21265452]]
0
[[0.19390246 0.20384888 0.21105418]]
1
[[0.19388804 0.20262899 0.20944162]]
1
[[0.19367135 0.2008377  0.20755461]]
0
[[0.19450939 0.1990831  0.20610668]]
0
[[0.19536717 0.19722442 0.20464495]]
2
[[0.1962535  0.19565375 0.20324524]]
0
[[0.19533141 0.1935032  0.2008934 ]]
1
[[0.19437031 0.19284384 0.19961445]]
1
[[0.19439588 0.19048126 0.19775431]]
1
[[0.19369544 0.18934134 0.19648324]]
2
[[0.19322364 0.18692778 0

[[0.23334815 0.22665413 0.24104781]]
2
[[0.2340812  0.22952211 0.24472193]]
2
[[0.2345864  0.230775   0.24685341]]
2
[[0.23562242 0.23172471 0.24865744]]
0
[[0.23736009 0.23308334 0.25089756]]
1
[[0.23598568 0.23304209 0.25074682]]
0
[[0.23742068 0.23423381 0.25243938]]
0
[[0.23931676 0.23507372 0.2539821 ]]
2
[[0.23974492 0.23507512 0.25408086]]
1
[[0.2400038  0.23605722 0.2545448 ]]
1
[[0.24012129 0.23784275 0.2553067 ]]
0
[[0.24105406 0.23965348 0.25638017]]
1
[[0.24256822 0.24155948 0.25765678]]
0
Buy: Rs.0.48
[[0.24355611 0.24327317 0.25857374]]
2
[[0.2436469  0.24412018 0.25833464]]
0
[[0.24437347 0.24484842 0.25830156]]
1
[[0.24501778 0.24559183 0.25830454]]
1
[[0.24573831 0.24578702 0.2580714 ]]
0
[[0.24492195 0.24635246 0.2575453 ]]
0
[[0.24478869 0.24615866 0.25688803]]
2
[[0.24318793 0.24643178 0.2557057 ]]
0
[[0.2416638  0.24546312 0.25385267]]
1
[[0.2400893  0.24572772 0.252962  ]]
1
[[0.24019256 0.2434689  0.25137195]]
1
[[0.23936155 0.24218854 0.25018704]]
2
[[0.23788226

[[0.29953793 0.29349032 0.310787  ]]
0
[[0.29984224 0.2931022  0.31187785]]
2
[[0.3002005 0.2957986 0.3154214]]
2
[[0.29974747 0.29641187 0.31674695]]
2
[[0.29929128 0.2964716  0.3172439 ]]
0
[[0.30060259 0.29703116 0.31858683]]
1
[[0.29850265 0.29613808 0.31736088]]
0
[[0.30010793 0.2967738  0.31848276]]
0
[[0.3023591  0.2970655  0.31953105]]
2
[[0.30242696 0.2961734  0.31854087]]
1
[[0.30233455 0.29662427 0.31811428]]
1
[[0.30211958 0.29811782 0.3181323 ]]
0
[[0.30205852 0.2997854  0.31839556]]
1
[[0.30256584 0.30135006 0.31877348]]
0
[[0.30236185 0.30324224 0.31913665]]
1
[[0.3019955  0.30408168 0.31885433]]
0
[[0.30308485 0.30575716 0.31970596]]
2
[[0.30397817 0.30610466 0.31966272]]
0
[[0.30289945 0.3073665  0.3194858 ]]
2
[[0.3030683  0.30772042 0.31926432]]
0
[[0.30384308 0.30858222 0.31963858]]
2
Sell: Rs.0.49 | Profit: Rs.0.01
[[0.3007153 0.3071748 0.3166505]]
0
[[0.2989684  0.30589736 0.3144122 ]]
1
[[0.29739898 0.30531648 0.31305307]]
1
[[0.2975003  0.30149323 0.31070712]]
1

[[0.22078028 0.22907913 0.23310253]]
0
[[0.22100084 0.22640163 0.23147488]]
2
[[0.22104701 0.22679114 0.23219685]]
2
[[0.22116005 0.22592501 0.23189932]]
2
[[0.22184849 0.22494784 0.23155476]]
0
[[0.22244167 0.22469498 0.2316625 ]]
1
[[0.22032236 0.2216608  0.22910786]]
0
[[0.2192708  0.2202512  0.22807814]]
0
[[0.21714422 0.21887483 0.22669116]]
2
[[0.2141565  0.21702299 0.2244234 ]]
1
[[0.21158135 0.21476577 0.22218196]]
1
[[0.20937228 0.21217042 0.21997221]]
0
[[0.2071363  0.21008217 0.21804814]]
1
[[0.20602404 0.20743309 0.21628118]]
0
[[0.20394942 0.20546451 0.21453317]]
1
[[0.2020335  0.20275813 0.21240608]]
0
[[0.20103808 0.20113015 0.2112987 ]]
2
[[0.20070721 0.19893584 0.21013072]]
0
[[0.19823855 0.19785823 0.20881397]]
2
[[0.1977591  0.1965436  0.20818688]]
0
[[0.19771813 0.19570424 0.20799357]]
2
[[0.19657418 0.19474481 0.20707704]]
2
[[0.19473319 0.19282433 0.20522262]]
2
[[0.1931876  0.19168258 0.20382501]]
2
[[0.19016166 0.18949081 0.2009862 ]]
0
[[0.18841293 0.18763691 0

[[0.09215871 0.08176658 0.10025567]]
0
[[0.09324046 0.08043018 0.09960955]]
0
[[0.09419999 0.07938027 0.09922885]]
2
[[0.09206744 0.07692952 0.09686974]]
1
Sell: Rs.0.49 | Profit: Rs.0.00
[[0.09234042 0.07810608 0.09675475]]
0
[[0.09453442 0.08021054 0.0979395 ]]
1
[[0.09513082 0.08284024 0.0982409 ]]
0
[[0.09633372 0.0859742  0.09940072]]
0
[[0.09633724 0.08847337 0.0999686 ]]
2
[[0.0954929  0.09019869 0.09985355]]
1
[[0.09518643 0.09267789 0.10023547]]
1
[[0.0951571  0.0954131  0.10084642]]
0
[[0.09491391 0.09783103 0.10132193]]
1
[[0.09617651 0.10023656 0.10232805]]
0
[[0.09603828 0.10207795 0.10271077]]
1
[[0.09574218 0.10253726 0.10241203]]
0
[[0.09703593 0.10388854 0.10318866]]
2
[[0.10040855 0.10550632 0.10487645]]
0
[[0.10071936 0.10688793 0.10557518]]
2
[[0.10510625 0.10964861 0.108405  ]]
0
[[0.10859231 0.11202265 0.11086039]]
2
[[0.1107151  0.11394903 0.11258993]]
2
[[0.11320646 0.11558408 0.11419103]]
2
[[0.11530668 0.11731732 0.1158524 ]]
2
[[0.11592351 0.11795682 0.116278

0
[[0.05908468 0.06113295 0.06328231]]
0
[[0.06053923 0.06123981 0.06376634]]
2
[[0.05979889 0.06085563 0.0630376 ]]
1
[[0.0593976  0.06048278 0.06250716]]
2
[[0.06035803 0.06014207 0.06250148]]
1
[[0.05923329 0.05970248 0.06174748]]
2
[[0.05817267 0.05913975 0.06086827]]
0
[[0.05809035 0.05861334 0.06040051]]
2
[[0.05776534 0.05813035 0.05988554]]
2
[[0.05622596 0.05733443 0.05862883]]
0
[[0.05492945 0.05673828 0.05766029]]
0
[[0.05334474 0.0562868  0.05671514]]
1
[[0.0530718  0.05540387 0.05602897]]
0
[[0.0516651  0.05493185 0.05524322]]
1
[[0.05055929 0.05378452 0.05419085]]
0
[[0.05037481 0.05316782 0.0538066 ]]
2
[[0.05232253 0.05274974 0.05440753]]
0
[[0.05141763 0.05268001 0.05431069]]
2
[[0.0538751  0.05289602 0.05565767]]
0
[[0.05575482 0.05317383 0.05689912]]
2
[[0.05675538 0.05342538 0.05775068]]
2
[[0.05837152 0.05357848 0.05870502]]
2
[[0.05984284 0.05402678 0.05984773]]
2
[[0.06043718 0.05399544 0.06023806]]
0
[[0.06064547 0.05402645 0.0606176 ]]
2
[[0.05975083 0.05387851

[[0.04582819 0.04485911 0.04708659]]
0
[[0.04545637 0.04454485 0.04691038]]
0
[[0.04419956 0.044597   0.04676041]]
2
[[0.04119032 0.04426409 0.04558514]]
1
[[0.03873526 0.04391637 0.04464117]]
2
[[0.03789228 0.04361378 0.04430223]]
1
[[0.03520196 0.04314201 0.04325569]]
2
[[0.03284988 0.0426003  0.04219855]]
0
[[0.03492959 0.04216173 0.04250482]]
2
[[0.03665365 0.04179432 0.04275684]]
2
[[0.03711174 0.04118656 0.04230087]]
0
[[0.03907713 0.04076662 0.04244502]]
0
[[0.0414659  0.0404231  0.04278056]]
2
[[0.04324975 0.04003926 0.04287131]]
0
[[0.04428361 0.03962888 0.042773  ]]
2
[[0.04480431 0.03929733 0.04256046]]
2
[[0.0457936  0.03883511 0.04242736]]
1
[[0.04566545 0.03915303 0.04227649]]
2
[[0.0460496  0.03942713 0.04233768]]
2
[[0.04911581 0.04015462 0.04386525]]
0
[[0.05099034 0.0408752  0.04510184]]
2
[[0.05273065 0.04175419 0.04644542]]
2
[[0.05586193 0.04272996 0.04842109]]
2
[[0.05961601 0.04418098 0.05107669]]
2
[[0.063345   0.04542194 0.05356456]]
0
[[0.06626273 0.04661711 0

[[0.02947551 0.03026549 0.03057108]]
0
[[0.02962651 0.02974012 0.03035387]]
0
[[0.02887172 0.029581   0.03015389]]
2
[[0.02648247 0.02913626 0.02904695]]
1
[[0.02456748 0.02863527 0.02813996]]
2
[[0.02426766 0.02821224 0.02788094]]
1
[[0.02213492 0.02770266 0.0269488 ]]
2
[[0.02047381 0.02718853 0.02612918]]
0
[[0.02219792 0.0267155  0.0263685 ]]
2
[[0.02371366 0.02634771 0.0266312 ]]
2
[[0.02412163 0.02580551 0.0262829 ]]
0
[[0.02507833 0.02540132 0.02623683]]
0
[[0.02595836 0.02505502 0.02622667]]
2
[[0.02648426 0.0247028  0.026071  ]]
0
[[0.02674168 0.02434247 0.02585899]]
2
[[0.02659137 0.02406076 0.02555805]]
2
[[0.0269725  0.02365749 0.02535076]]
1
[[0.02623856 0.02367241 0.0249986 ]]
2
[[0.02638513 0.02340985 0.02474489]]
0
[[0.02576951 0.02348322 0.02454682]]
1
[[0.02537947 0.02344927 0.02426021]]
0
[[0.02323289 0.02361009 0.02361804]]
1
[[0.02323143 0.02353018 0.02357057]]
0
[[0.02218215 0.02347115 0.02320075]]
2
[[0.0203773  0.02347144 0.02256726]]
0
Buy: Rs.0.47
[[0.02022511

[[0.01824695 0.02126826 0.02096626]]
1
[[0.0209749  0.02049707 0.02155641]]
0
Sell: Rs.0.52 | Profit: Rs.0.05
[[0.01905809 0.02025648 0.02087602]]
0
[[0.01974651 0.02004576 0.02115869]]
2
[[0.01876637 0.01959867 0.02055456]]
1
[[0.0181134  0.01922814 0.020129  ]]
2
[[0.01893623 0.0189204  0.02030326]]
1
[[0.01787249 0.01870089 0.01983005]]
2
[[0.01709235 0.01843107 0.01937273]]
0
[[0.01790857 0.01815167 0.01945558]]
2
[[0.0186237  0.01796094 0.01958757]]
2
[[0.01838335 0.01760903 0.01916878]]
0
[[0.01830259 0.01736241 0.01892388]]
0
[[0.01816865 0.01715602 0.01871044]]
2
[[0.01782729 0.01694282 0.01840017]]
0
[[0.01766105 0.01671575 0.01815276]]
2
[[0.01708597 0.01654063 0.01778688]]
2
[[0.01697792 0.0162171  0.01745438]]
1
[[0.01579803 0.01616055 0.0169437 ]]
2
[[0.01542075 0.01581569 0.01646992]]
0
[[0.01504123 0.01580451 0.0162641 ]]
1
[[0.01486918 0.01552882 0.01593451]]
0
[[0.01385347 0.0154685  0.01551244]]
1
[[0.01483294 0.01519428 0.01565596]]
0
[[0.01507121 0.0149678  0.015574

[[0.33772594 0.3397633  0.350545  ]]
0
[[0.33412126 0.3358405  0.3464355 ]]
2
[[0.33011374 0.33262888 0.34232837]]
1
[[0.32779008 0.32705003 0.33764482]]
0
[[0.320907   0.3236034  0.33264866]]
2
[[0.31740287 0.32063428 0.32990476]]
2
[[0.3272578  0.3256764  0.33923185]]
0
[[0.3319628 0.327581  0.3444213]]
2
[[0.33655414 0.33324412 0.35262254]]
1
[[0.3412552  0.33648753 0.3590817 ]]
2
[[0.34873974 0.33918774 0.36577457]]
2
Buy: Rs.0.54
[[0.34919718 0.34085622 0.36843443]]
2
[[0.35018447 0.34176207 0.3703373 ]]
2
[[0.34873408 0.34070998 0.36952433]]
0
[[0.34841743 0.34018132 0.3694117 ]]
0
[[0.3488839  0.33980572 0.36961803]]
2
[[0.347681   0.33843315 0.36812398]]
0
[[0.3471888  0.33707553 0.36688954]]
2
[[0.344948   0.33492503 0.364105  ]]
2
[[0.34112906 0.33138275 0.3594809 ]]
1
[[0.33751875 0.33002144 0.35617048]]
2
[[0.33321896 0.3273897  0.3515337 ]]
0
[[0.33031553 0.32578558 0.34822974]]
1
[[0.3267726  0.32438782 0.3447867 ]]
0
[[0.32440573 0.32355842 0.34227926]]
1
[[0.3224188  0.

[[0.30069122 0.30235466 0.3133562 ]]
1
[[0.29973847 0.29988903 0.31107146]]
0
[[0.29794824 0.29769728 0.30875307]]
2
[[0.29588985 0.29625094 0.30662358]]
1
[[0.29536587 0.29275233 0.30399907]]
0
[[0.29075298 0.29122558 0.3011213 ]]
2
[[0.28860018 0.28959996 0.29961577]]
2
[[0.2973849  0.2941316  0.30750906]]
0
[[0.30154634 0.29603463 0.31189564]]
2
[[0.30502912 0.30095583 0.3183921 ]]
1
[[0.30862373 0.30364004 0.3233547 ]]
2
[[0.31542605 0.30601782 0.32903904]]
2
[[0.31631932 0.30827385 0.3319157 ]]
1
[[0.31550196 0.30864137 0.33266965]]
2
[[0.31775808 0.3113206  0.33584338]]
2
[[0.31937903 0.3129248  0.33780912]]
2
[[0.3179571  0.3127835  0.33717418]]
1
[[0.3171996  0.31204075 0.33622512]]
2
[[0.3154087  0.3122869  0.33528587]]
2
[[0.31156942 0.31157538 0.33271006]]
2
[[0.30740854 0.30958575 0.32901955]]
1
[[0.30341503 0.30867016 0.32608113]]
2
[[0.299224   0.30675012 0.32228452]]
0
[[0.29769233 0.30568698 0.320024  ]]
1
[[0.295451   0.30404854 0.31726873]]
0
[[0.29530403 0.30290484 0

[[0.25109893 0.2567627  0.26388317]]
1
[[0.25125548 0.2532892  0.26159152]]
0
[[0.24822848 0.2517532  0.259278  ]]
2
[[0.24717078 0.24990797 0.25794813]]
2
[[0.25520498 0.25298348 0.26419273]]
0
[[0.25942022 0.253982   0.26763225]]
2
[[0.2626479  0.25753644 0.27264047]]
1
[[0.2659286  0.2592029  0.27637368]]
2
[[0.27257988 0.26065502 0.28105828]]
2
[[0.27374086 0.262434   0.2834915 ]]
1
[[0.27360278 0.2625245  0.28415486]]
2
[[0.27627832 0.26481575 0.28710663]]
2
[[0.27863553 0.26631373 0.28925592]]
2
[[0.27825102 0.26651317 0.28932062]]
1
[[0.27860823 0.26615804 0.28912908]]
2
[[0.27801168 0.26686257 0.2890749 ]]
2
[[0.2754827  0.26613095 0.28722185]]
2
[[0.2735821  0.26586184 0.28579792]]
0
[[0.27156237 0.26538852 0.28429273]]
2
[[0.268479  0.2648447 0.2822116]]
2
[[0.26497778 0.26400864 0.2796897 ]]
2
[[0.2628703  0.2625206  0.27724844]]
2
[[0.25897163 0.26136205 0.27422494]]
1
Sell: Rs.0.59 | Profit: Rs.0.00
[[0.25427118 0.25850603 0.26996368]]
0
[[0.25209838 0.2567375  0.26739952]

[[0.21525823 0.2223055  0.22840235]]
1
[[0.21387538 0.21972851 0.2260505 ]]
0
[[0.21126679 0.21878767 0.22418854]]
2
[[0.2108323  0.21728681 0.22321157]]
2
[[0.21606669 0.22012599 0.2278949 ]]
0
[[0.22073977 0.22092524 0.2310456 ]]
2
[[0.22297025 0.22407147 0.23499353]]
1
[[0.2262018  0.22526631 0.23810785]]
2
[[0.2319068  0.22635904 0.24194202]]
2
[[0.23330422 0.22793043 0.24415588]]
1
[[0.23397489 0.22763962 0.24482962]]
2
[[0.23668817 0.22953236 0.24748257]]
2
[[0.23885304 0.23086995 0.24943908]]
2
[[0.23915724 0.2311337  0.24986523]]
1
[[0.24011385 0.23063047 0.24993181]]
2
[[0.24010682 0.23126233 0.25019553]]
2
[[0.23884983 0.23064135 0.24909802]]
2
[[0.23777635 0.23055336 0.24831045]]
0
[[0.23692226 0.23025265 0.24754901]]
2
[[0.23489404 0.22999252 0.24626018]]
2
[[0.2329335  0.22947752 0.24477062]]
2
[[0.2317343  0.22847247 0.24322602]]
2
[[0.22912014 0.2278594  0.24129817]]
1
[[0.22624311 0.22614162 0.23863867]]
2
[[0.2240062  0.22499633 0.23652638]]
1
[[0.22228321 0.22355908 0

[[0.06919764 0.07440273 0.07658543]]
1
[[0.06802582 0.07335975 0.07545219]]
2
[[0.06544891 0.07228936 0.07373334]]
0
[[0.06307507 0.07124612 0.07205757]]
2
[[0.06186717 0.0706621  0.07110377]]
2
[[0.05999546 0.0698367  0.06974288]]
2
[[0.05770517 0.06886242 0.06812625]]
2
Buy: Rs.0.54
[[0.0578176  0.06881611 0.06799565]]
1
[[0.05285268 0.06671794 0.06475711]]
2
[[0.04956438 0.06528065 0.0625606 ]]
2
[[0.04826949 0.064623   0.06160822]]
1
[[0.04646729 0.06370264 0.06035887]]
2
[[0.04350909 0.06236412 0.05841067]]
2
[[0.04189309 0.06155908 0.05730668]]
2
[[0.04039501 0.0608179  0.05629251]]
1
[[0.03855415 0.05987538 0.05507645]]
2
[[0.03776318 0.05935764 0.05452575]]
2
[[0.03748928 0.05905878 0.05431096]]
2
[[0.03665616 0.05856585 0.05376551]]
0
[[0.04071478 0.05969087 0.05580563]]
2
[[0.04516309 0.06100638 0.0581369 ]]
2
[[0.04849554 0.06193381 0.05982007]]
2
[[0.05100893 0.06258281 0.06102909]]
2
[[0.05409634 0.06348139 0.0626173 ]]
1
[[0.05643697 0.06403705 0.06377676]]
2
[[0.05702467

[[0.02334832 0.02302703 0.02367051]]
2
[[0.02329264 0.02299208 0.02362675]]
2
[[0.0232425  0.02296061 0.02358025]]
1
[[0.02319735 0.02291526 0.02353837]]
1
[[0.02315669 0.0228576  0.02350066]]
2
[[0.02312008 0.02280567 0.02345963]]
0
[[0.02305393 0.02275891 0.02342268]]
2
[[0.02299436 0.02271681 0.02338236]]
2
[[0.02294073 0.0226789  0.02333899]]
2
[[0.02289243 0.02264476 0.0232929 ]]
2
[[0.02284894 0.02261402 0.02324437]]
1
[[0.02280977 0.02257011 0.02320067]]
0
[[0.02274379 0.02253057 0.02316132]]
1
[[0.02268437 0.02247886 0.02312589]]
2
[[0.02263087 0.02243229 0.02308699]]
1
[[0.02258269 0.02237509 0.02305196]]
2
[[0.02253931 0.02232357 0.02301344]]
2
Buy: Rs.0.50
[[0.02250025 0.02227719 0.02297178]]
1
[[0.02246507 0.02222152 0.02293427]]
2
[[0.0224334  0.02217139 0.02289353]]
2
[[0.02240488 0.02212625 0.02284991]]
2
[[0.0223792  0.0220856  0.02280369]]
0
[[0.02232734 0.022049   0.02276208]]
2
[[0.02228064 0.02201604 0.02271769]]
2
[[0.02223859 0.02198637 0.02267081]]
2
[[0.02220073

[[0.01565857 0.01526102 0.01566763]]
2
[[0.01561919 0.01523134 0.01563305]]
2
[[0.01558373 0.01520462 0.01559668]]
1
[[0.0155518  0.01516743 0.01556394]]
1
[[0.01552305 0.01512103 0.01553445]]
2
[[0.01549716 0.01507924 0.01550269]]
0
[[0.01543975 0.01504162 0.01547409]]
2
[[0.01538805 0.01500774 0.01544314]]
2
[[0.0153415  0.01497723 0.01541009]]
2
[[0.01529958 0.01494976 0.01537515]]
2
[[0.01526184 0.01492502 0.01533852]]
1
[[0.01522785 0.01489074 0.01530554]]
0
[[0.0151667  0.01485988 0.01527584]]
1
[[0.01511162 0.01482025 0.0152491 ]]
2
[[0.01506204 0.01478457 0.01521988]]
1
[[0.01501738 0.01474136 0.01519358]]
2
[[0.01497717 0.01470245 0.01516476]]
2
[[0.01494097 0.01466741 0.0151337 ]]
1
[[0.01490836 0.01462596 0.01510574]]
2
[[0.01487901 0.01458863 0.01507545]]
2
[[0.01485257 0.01455502 0.01504309]]
2
[[0.01482877 0.01452476 0.01500886]]
2
[[0.01480734 0.01449751 0.01497297]]
2
[[0.01478803 0.01447297 0.01493558]]
2
[[0.01477065 0.01445087 0.01489686]]
2
[[0.01475501 0.01443097 0

[[0.0095091  0.00942059 0.01011976]]
2
[[0.00949142 0.00940669 0.01030246]]
1
[[0.00947549 0.0094085  0.01046697]]
1
[[0.00946115 0.00943029 0.0106151 ]]
2
[[0.00944823 0.00944991 0.01074455]]
0
[[0.00947401 0.00946758 0.0108611 ]]
2
[[0.00949723 0.00948349 0.01096201]]
2
[[0.00951813 0.00949781 0.0110488 ]]
2
[[0.00953696 0.00951071 0.01112282]]
2
[[0.00955391 0.00952233 0.01118533]]
1
[[0.00956917 0.00957451 0.01124162]]
0
[[0.00963779 0.0096215  0.01129231]]
1
[[0.00969958 0.00970566 0.01133795]]
2
[[0.00975522 0.00978144 0.01137481]]
1
[[0.00980532 0.00988849 0.011408  ]]
2
[[0.00985044 0.00998487 0.01143362]]
2
[[0.00989106 0.01007166 0.01145241]]
1
[[0.00992764 0.01018046 0.01146933]]
2
[[0.00996058 0.01027844 0.01148027]]
2
[[0.00999024 0.01036665 0.01148582]]
2
[[0.01001695 0.01044609 0.01148651]]
2
[[0.01004099 0.01051762 0.01148282]]
2
[[0.01006265 0.01058203 0.01147519]]
2
[[0.01008215 0.01064003 0.01146401]]
2
[[0.01009971 0.01069225 0.01144964]]
2
[[0.01011552 0.01073928 0

[[0.01891982 0.01940065 0.02019588]]
2
[[0.01893432 0.01941195 0.02040094]]
2
[[0.01894737 0.01942212 0.02057737]]
1
[[0.01895913 0.01943657 0.02073624]]
2
[[0.01896971 0.01944958 0.02087093]]
0
[[0.01902612 0.0194613  0.02099222]]
2
[[0.01907691 0.01947185 0.02109295]]
2
[[0.01912265 0.01948135 0.02117514]]
2
[[0.01916383 0.0194899  0.0212406 ]]
2
[[0.01920092 0.0194976  0.02129095]]
2
[[0.01923431 0.01950454 0.02132768]]
1
[[0.01926438 0.01954257 0.02136075]]
0
[[0.01934785 0.01957681 0.02139053]]
1
[[0.01942301 0.01963892 0.02141735]]
2
[[0.01949069 0.01969486 0.02143282]]
1
[[0.01955163 0.01977326 0.02144674]]
2
[[0.01960651 0.01984385 0.02145058]]
2
[[0.01965592 0.01990742 0.02144534]]
1
[[0.01970041 0.01998429 0.02144061]]
2
[[0.01974048 0.0200535  0.02142764]]
2
[[0.01977656 0.02011582 0.02140726]]
2
[[0.01980904 0.02017194 0.0213802 ]]
2
[[0.0198383  0.02022247 0.02134713]]
2
[[0.01986464 0.02026798 0.02130866]]
2
[[0.01988835 0.02030895 0.02126534]]
2
[[0.01990971 0.02034584 0

[[0.02763389 0.02861448 0.03055522]]
0
[[0.02775771 0.02869386 0.03052637]]
2
[[0.02786921 0.02876533 0.03078973]]
2
[[0.02796961 0.0288297  0.03101355]]
2
[[0.02806002 0.02888765 0.03120168]]
1
[[0.02814142 0.02897484 0.03137109]]
2
[[0.02821473 0.02905335 0.03151005]]
0
[[0.02838477 0.02912404 0.03163518]]
2
[[0.02853789 0.02918769 0.03173414]]
2
[[0.02867577 0.02924501 0.0318095 ]]
2
[[0.02879992 0.02929663 0.03186355]]
2
[[0.02891172 0.0293431  0.0318984 ]]
1
[[0.02901238 0.02942969 0.03192978]]
1
[[0.02910302 0.02954976 0.03195803]]
2
[[0.02918465 0.02965788 0.03222952]]
0
[[0.02934518 0.02975524 0.03247397]]
2
[[0.02948973 0.02984291 0.03268001]]
1
[[0.02961989 0.02997801 0.03286554]]
2
[[0.02973709 0.03009967 0.03301833]]
2
[[0.02984263 0.03020921 0.03314156]]
1
[[0.02993766 0.03036746 0.03325253]]
2
[[0.03002323 0.03050996 0.033338  ]]
2
[[0.03010029 0.03063827 0.03340045]]
2
[[0.03016967 0.03075381 0.03344215]]
2
[[0.03023215 0.03085785 0.03346513]]
2
[[0.03028841 0.03095153 0

[[0.04310435 0.04299595 0.04542116]]
0
[[0.04314002 0.0430388  0.04534439]]
2
[[0.04317214 0.04307738 0.04557332]]
2
[[0.04320107 0.04311212 0.04575872]]
2
[[0.04322711 0.0431434  0.04590483]]
1
[[0.04325056 0.04319556 0.04603639]]
2
[[0.04327168 0.04324254 0.04613388]]
0
[[0.0433279  0.04328483 0.04622166]]
2
[[0.04337853 0.04332292 0.04627962]]
2
[[0.04342411 0.04335722 0.04631068]]
2
[[0.04346516 0.04338809 0.04631751]]
2
[[0.04350213 0.0434159  0.0463025 ]]
1
[[0.04353541 0.04347046 0.04628898]]
1
[[0.04356538 0.04354563 0.04627681]]
2
[[0.04359236 0.04361333 0.0465184 ]]
0
[[0.04365702 0.04367428 0.04673595]]
2
[[0.04371523 0.04372916 0.04691049]]
2
[[0.04376766 0.04377859 0.04704624]]
2
[[0.04381486 0.04382309 0.04714697]]
0
[[0.04392302 0.04386316 0.04723768]]
1
[[0.04402042 0.04395175 0.04731936]]
2
[[0.04410812 0.04403152 0.04737125]]
2
[[0.0441871  0.04410335 0.04739628]]
1
Sell: Rs.0.40 | Profit: -Rs.0.00
[[0.0442582  0.04421596 0.04741883]]
2
[[0.04432223 0.04431736 0.04741

[[0.05219741 0.05230158 0.05482   ]]
2
[[0.0522038  0.05232397 0.05499072]]
2
[[0.05220956 0.05234412 0.0551182 ]]
1
[[0.05221475 0.05236331 0.055233  ]]
2
[[0.05221941 0.05238059 0.05531   ]]
0
[[0.05224777 0.05239615 0.05537933]]
2
[[0.05227331 0.05241016 0.0554153 ]]
2
[[0.05229631 0.05242277 0.05542118]]
2
[[0.05231701 0.05243413 0.05539998]]
2
[[0.05233566 0.05244436 0.05535437]]
1
[[0.05235245 0.05246172 0.0553133 ]]
1
[[0.05236756 0.05248229 0.05527632]]
2
[[0.05238118 0.05250081 0.05550332]]
0
[[0.05241932 0.05251749 0.05570772]]
2
[[0.05245367 0.05253251 0.05586513]]
2
[[0.05248459 0.05254603 0.05598014]]
2
[[0.05251244 0.0525582  0.05605692]]
0
[[0.05259294 0.05256917 0.05612605]]
1
[[0.05266543 0.05262224 0.0561883 ]]
2
[[0.05273071 0.05267004 0.05621742]]
2
[[0.05278949 0.05271307 0.05621668]]
1
[[0.05284241 0.05279176 0.05621602]]
2
[[0.05289007 0.05286261 0.05618845]]
2
[[0.05293298 0.05292641 0.05613664]]
2
[[0.05297162 0.05298385 0.05606302]]
2
[[0.05300642 0.05303558 0

[[0.04365607 0.04372543 0.04555472]]
2
[[0.04363364 0.04370005 0.0453872 ]]
0
[[0.04357112 0.04367719 0.04523636]]
2
[[0.04351482 0.04365661 0.04507748]]
0
[[0.04340737 0.04363807 0.04493441]]
2
[[0.04331061 0.04362138 0.04478265]]
2
[[0.04322348 0.04360636 0.04462314]]
2
[[0.04314503 0.04359282 0.04445671]]
2
[[0.04307438 0.04358064 0.04428413]]
1
[[0.04301077 0.04347395 0.04412873]]
1
[[0.04295349 0.04327962 0.04398881]]
2
[[0.04290192 0.04310463 0.04414677]]
0
[[0.04277615 0.04294706 0.04428901]]
2
[[0.0426629  0.04280518 0.04439448]]
2
[[0.04256092 0.04267742 0.04446679]]
2
[[0.0424691  0.04256238 0.04450919]]
0
[[0.0423711  0.04245879 0.04454736]]
1
[[0.04228286 0.04235668 0.04458174]]
2
[[0.0422034  0.04226475 0.04458989]]
2
[[0.04213186 0.04218196 0.0445744 ]]
1
[[0.04206743 0.04211784 0.04456046]]
2
[[0.04200942 0.04206011 0.04452508]]
2
[[0.04195718 0.04200812 0.0444704 ]]
2
[[0.04191015 0.0419613  0.04439836]]
2
[[0.0418678  0.04191915 0.04431071]]
2
[[0.04182966 0.0418812  0

[[0.03275712 0.03293089 0.03452818]]
2
[[0.03274098 0.03293094 0.0344087 ]]
2
[[0.03272644 0.03293097 0.03428227]]
0
[[0.03269897 0.03293101 0.03416844]]
2
[[0.03267423 0.03293104 0.03404723]]
2
[[0.03265196 0.03293107 0.03391942]]
2
[[0.0326319  0.03293109 0.03378575]]
2
[[0.03261384 0.03293112 0.03364685]]
2
[[0.03259758 0.03293114 0.03350332]]
1
[[0.03258294 0.03285397 0.03337407]]
2
[[0.03256975 0.03278449 0.03323937]]
2
[[0.03255788 0.03272192 0.0330998 ]]
2
[[0.03254719 0.03266558 0.03328494]]
0
[[0.03245299 0.03261485 0.03345165]]
2
[[0.03236816 0.03256917 0.03358343]]
2
[[0.03229178 0.03252804 0.03368369]]
2
[[0.032223   0.032491   0.03375551]]
0
[[0.03214687 0.03245765 0.03382017]]
1
[[0.03207831 0.03240453 0.0338784 ]]
2
[[0.03201658 0.03235669 0.03391223]]
2
[[0.03196099 0.03231362 0.03392406]]
1
[[0.03191094 0.0322688  0.03393471]]
2
[[0.03186587 0.03222844 0.03392565]]
2
[[0.03182529 0.0321921  0.03389882]]
2
[[0.03178875 0.03215938 0.033856  ]]
2
[[0.03175584 0.03212991 0

[[0.01623391 0.01538058 0.01598134]]
2
[[0.01621418 0.0153303  0.01590366]]
2
[[0.01619641 0.01528503 0.01582766]]
2
[[0.01618042 0.01524426 0.0157539 ]]
0
[[0.016085   0.01520755 0.01568749]]
2
[[0.01599907 0.01517449 0.01562276]]
2
[[0.0159217  0.01514473 0.01555935]]
2
[[0.01585204 0.01511792 0.015497  ]]
2
[[0.01578931 0.01509379 0.01543556]]
2
[[0.01573282 0.01507206 0.01537495]]
1
[[0.01568196 0.01504277 0.01532038]]
2
[[0.01563616 0.0150164  0.01526611]]
2
[[0.01559491 0.01499265 0.01521225]]
2
[[0.01555778 0.01497127 0.01515892]]
0
[[0.01544608 0.01495201 0.01511091]]
2
[[0.0153455  0.01493467 0.01506235]]
1
[[0.01525493 0.01489146 0.01501864]]
1
[[0.01517338 0.01482161 0.01497927]]
2
[[0.01509994 0.01475871 0.01493695]]
2
[[0.01503382 0.01470207 0.01489163]]
2
[[0.01497428 0.01465107 0.01484339]]
2
[[0.01492066 0.01460515 0.01479243]]
1
[[0.01487239 0.01453036 0.01474653]]
2
[[0.01482892 0.01446302 0.01469766]]
2
[[0.01478977 0.01440238 0.01464621]]
2
[[0.01475453 0.01434778 0

[[0.00628151 0.00631443 0.00630943]]
2
[[0.00626661 0.00629914 0.00627272]]
2
[[0.0062532  0.00628537 0.0062358 ]]
0
[[0.00620981 0.00627298 0.00620255]]
2
[[0.00617073 0.00626181 0.00616934]]
2
[[0.00613555 0.00625176 0.00613647]]
2
[[0.00610387 0.00624271 0.00610422]]
2
[[0.00607534 0.00623456 0.00607284]]
2
[[0.00604965 0.00622722 0.00604257]]
1
[[0.00602652 0.00619394 0.00601531]]
2
[[0.00600569 0.00616397 0.00598899]]
2
[[0.00598694 0.00613699 0.0059635 ]]
2
[[0.00597005 0.00611269 0.00593875]]
0
[[0.00593666 0.00609081 0.00591646]]
2
[[0.00590659 0.00607111 0.00589464]]
1
[[0.00587952 0.00602729 0.00587498]]
1
[[0.00585514 0.00596193 0.00585728]]
2
[[0.00583319 0.00590308 0.00583873]]
2
[[0.00581342 0.00585009 0.0058189 ]]
0
[[0.005767   0.00580237 0.00580105]]
2
[[0.00572519 0.0057594  0.00578106]]
2
[[0.00568755 0.00572071 0.00575914]]
2
[[0.00565365 0.00568587 0.0057355 ]]
2
[[0.00562313 0.0056545  0.00571032]]
2
[[0.00559565 0.00562625 0.00568377]]
2
[[0.0055709  0.00560081 0

[[0.00227413 0.00230428 0.00230756]]
2
[[0.00226262 0.00229862 0.00229327]]
0
[[0.00224253 0.00229351 0.0022804 ]]
2
[[0.00222444 0.00228892 0.00226729]]
2
[[0.00220814 0.00228478 0.00225411]]
2
[[0.00219347 0.00228106 0.00224099]]
2
[[0.00218026 0.00227771 0.00222806]]
2
[[0.00216837 0.00227469 0.00221547]]
1
[[0.00215766 0.00226114 0.00220412]]
2
[[0.00214801 0.00224895 0.00219307]]
2
[[0.00213933 0.00223797 0.00218227]]
2
[[0.00213151 0.00222809 0.0021717 ]]
0
[[0.00212263 0.00221919 0.00216219]]
2
[[0.00211463 0.00221117 0.00215281]]
1
[[0.00210743 0.0021934  0.00214436]]
1
[[0.00210095 0.00216693 0.00213676]]
2
[[0.00209512 0.0021431  0.00212874]]
2
[[0.00208986 0.00212163 0.00212012]]
0
[[0.00207589 0.00210231 0.00211236]]
2
[[0.00206331 0.0020849  0.00210378]]
2
[[0.00205199 0.00206923 0.00209447]]
2
[[0.00204179 0.00205512 0.00208451]]
2
[[0.0020326  0.00204242 0.00207398]]
2
[[0.00202434 0.00203098 0.00206292]]
2
[[0.00201689 0.00202068 0.00205141]]
2
[[0.00201019 0.0020114  0

[[0.00064513 0.00064777 0.00065898]]
2
[[0.00064035 0.00064585 0.00065426]]
2
[[0.00063604 0.00064412 0.00064947]]
1
[[0.00063217 0.00063971 0.00064516]]
2
[[0.00062867 0.00063573 0.00064074]]
2
[[0.00062553 0.00063215 0.00063623]]
2
[[0.0006227  0.00062893 0.00063164]]
2
[[0.00062015 0.00062602 0.00062698]]
2
[[0.00061785 0.00062341 0.00062227]]
1
[[0.00061579 0.00061776 0.00061802]]
2
[[0.00061392 0.00061268 0.00061368]]
2
[[0.00061225 0.0006081  0.00060927]]
2
[[0.00061074 0.00060397 0.00060484]]
0
[[0.00060518 0.00060026 0.00060084]]
2
[[0.00060017 0.00059692 0.00059682]]
1
[[0.00059566 0.00059107 0.00059319]]
1
[[0.00059159 0.00058313 0.00058993]]
2
[[0.00058794 0.00057598 0.00058652]]
2
[[0.00058464 0.00056955 0.00058298]]
0
[[0.00057764 0.00056375 0.0005798 ]]
2
[[0.00057134 0.00055853 0.00057645]]
2
[[0.00056566 0.00055383 0.00057295]]
2
[[0.00056055 0.0005496  0.00056932]]
2
[[0.00055594 0.00054579 0.00056557]]
2
[[0.0005518  0.00054236 0.00056173]]
2
[[0.00054807 0.00053927 0

[[0.00016086 0.0001556  0.0001698 ]]
2
[[0.00016039 0.00015498 0.00016856]]
2
[[0.00015997 0.00015442 0.00016729]]
2
[[0.00015959 0.00015391 0.00016599]]
1
[[0.00015925 0.0001539  0.00016482]]
2
[[0.00015895 0.00015389 0.00016362]]
2
[[0.00015867 0.00015388 0.00016238]]
2
[[0.00015842 0.00015387 0.00016112]]
2
[[0.0001582  0.00015386 0.00015984]]
2
[[0.000158   0.00015385 0.00015853]]
2
[[0.00015781 0.00015385 0.00015721]]
1
[[0.00015765 0.00015338 0.00015602]]
1
[[0.0001575  0.00015253 0.00015495]]
1
[[0.00015737 0.00015143 0.00015399]]
0
[[0.00015605 0.00015044 0.00015312]]
0
[[0.00015366 0.00014955 0.00015233]]
2
[[0.00015152 0.00014874 0.00015151]]
1
[[0.00014958 0.00014745 0.00015077]]
2
[[0.00014784 0.00014629 0.00014997]]
2
[[0.00014627 0.00014524 0.0001491 ]]
0
[[0.00014415 0.0001443  0.00014832]]
2
[[0.00014224 0.00014345 0.00014748]]
2
[[0.00014052 0.00014269 0.00014659]]
2
[[0.00013897 0.000142   0.00014565]]
2
[[0.00013758 0.00014138 0.00014467]]
2
[[0.00013632 0.00014082 0

[[0.00718844 0.00742738 0.00792328]]
0
[[0.00733462 0.00775982 0.00794249]]
0
[[0.00750111 0.00805915 0.0079598 ]]
2
[[0.00765103 0.00832869 0.0079693 ]]
0
[[0.00782928 0.0085714  0.00797786]]
2
[[0.00798978 0.00878995 0.00798887]]
1
[[0.0081343  0.00893054 0.00799879]]
2
[[0.00826444 0.00905714 0.00831644]]
2
[[0.00838162 0.00917113 0.00890472]]
2
Buy: Rs.0.52
[[0.00848714 0.00927378 0.00943062]]
2
[[0.00858215 0.00936621 0.00989479]]
2
[[0.0086677  0.00944944 0.01030292]]
2
[[0.00874474 0.00952438 0.01066016]]
2
[[0.0088141  0.00959186 0.01097123]]
2
[[0.00887657 0.00965263 0.01124041]]
2
[[0.00893281 0.00970734 0.01147158]]
0
[[0.00930886 0.00975661 0.01167975]]
2
[[0.00964748 0.00980097 0.01185554]]
2
[[0.00995239 0.00984092 0.012002  ]]
2
[[0.01022695 0.00987689 0.0121219 ]]
2
[[0.01047417 0.00990928 0.01221776]]
1
[[0.01069678 0.01015643 0.01230407]]
2
[[0.01089723 0.01037898 0.01236949]]
2
[[0.01107773 0.01057937 0.01241602]]
2
[[0.01124026 0.01075981 0.0124455 ]]
2
[[0.01138661

[[0.02098859 0.02164742 0.02251266]]
2
[[0.02072588 0.02151484 0.02289761]]
1
[[0.02048932 0.02142774 0.02324425]]
2
[[0.02027632 0.02134932 0.02373207]]
2
[[0.02008452 0.0212787  0.02414764]]
2
[[0.01991181 0.02121511 0.02404124]]
2
[[0.01975629 0.02115785 0.02392171]]
2
[[0.01961626 0.02110629 0.02379047]]
0
[[0.01998798 0.02105986 0.02367229]]
2
[[0.0203227  0.02101805 0.02354248]]
2
[[0.0206241  0.02098041 0.02340233]]
2
[[0.0208955  0.02094651 0.02325298]]
2
[[0.02113987 0.02091599 0.02309549]]
1
[[0.02135992 0.02102818 0.02295368]]
2
[[0.02155807 0.0211292  0.02280325]]
2
[[0.02173649 0.02122016 0.02264521]]
2
[[0.02189714 0.02130207 0.02248044]]
2
[[0.02204181 0.02137583 0.02230979]]
2
[[0.02217207 0.02144224 0.02213398]]
2
[[0.02228936 0.02150204 0.02195442]]
1
[[0.02239498 0.02151115 0.02179273]]
1
[[0.02249009 0.02148707 0.02164714]]
1
[[0.02257572 0.02144877 0.02151605]]
0
[[0.02246394 0.02141428 0.021398  ]]
0
[[0.02217588 0.02138322 0.02129171]]
2
[[0.02191649 0.02135526 0

[[0.02689163 0.02969542 0.02779698]]
1
[[0.02663116 0.02953783 0.02828076]]
2
[[0.02639662 0.02939593 0.02889917]]
2
[[0.02618542 0.02926815 0.02943774]]
2
[[0.02599525 0.0291531  0.02937075]]
2
[[0.02582402 0.02904949 0.02928325]]
2
[[0.02566982 0.0289562  0.02917735]]
2
[[0.02553098 0.0288722  0.02905496]]
0
[[0.02573765 0.02879656 0.02894476]]
0
[[0.02620328 0.02872845 0.02884553]]
2
[[0.02662255 0.02866712 0.02872941]]
0
[[0.02710668 0.0286119  0.02862486]]
2
[[0.02754262 0.02856217 0.02850413]]
1
Sell: Rs.0.49 | Profit: Rs.0.00
[[0.02793516 0.02831459 0.02839542]]
2
[[0.02828862 0.02809165 0.02827114]]
2
[[0.0286069  0.02789091 0.02813325]]
2
[[0.02889349 0.02771015 0.02799129]]
2
[[0.02915155 0.02754739 0.02785336]]
2
[[0.02938393 0.02740083 0.02772619]]
1
[[0.02959316 0.0273421  0.02761168]]
1
[[0.02978157 0.02739914 0.02750857]]
1
[[0.02995123 0.02757768 0.02741573]]
0
[[0.02986433 0.02773845 0.02733213]]
0
[[0.02954832 0.02788321 0.02725685]]
2
[[0.02926377 0.02801356 0.027204

[[0.02252832 0.02547821 0.02634178]]
1
[[0.02222474 0.02534073 0.02665971]]
2
[[0.02195138 0.02521694 0.02710035]]
2
[[0.02170523 0.02510547 0.02747292]]
2
[[0.02148358 0.0250051  0.02731938]]
2
[[0.021284   0.02491472 0.02715699]]
2
[[0.02110429 0.02483333 0.02698678]]
2
[[0.02094247 0.02476005 0.02680966]]
0
[[0.02144828 0.02469406 0.02665017]]
0
[[0.02244308 0.02463464 0.02650656]]
2
[[0.02333885 0.02458114 0.02635379]]
0
[[0.02438227 0.02453296 0.02621622]]
2
[[0.02532181 0.02448958 0.02606911]]
1
[[0.02616783 0.02449247 0.02593665]]
2
[[0.02692962 0.02449508 0.02579827]]
0
[[0.02742459 0.02449742 0.02567367]]
0
[[0.02767649 0.02449953 0.02556146]]
0
[[0.0277084  0.02450143 0.02546043]]
2
[[0.02773714 0.02450314 0.02538479]]
0
[[0.02756824 0.02450468 0.02531668]]
0
[[0.02722316 0.02450607 0.02525535]]
1
[[0.02691244 0.02471373 0.02520013]]
0
[[0.02644462 0.02490073 0.0251504 ]]
0
[[0.02583906 0.0250691  0.02510563]]
2
[[0.02529379 0.02522072 0.02505535]]
0
[[0.02462669 0.02535724 0

[[0.02126539 0.02215411 0.02372522]]
2
[[0.02102387 0.02194115 0.02413964]]
2
[[0.02080639 0.02174938 0.02449175]]
1
[[0.02061056 0.02182509 0.0248088 ]]
2
[[0.02043422 0.02189326 0.02524673]]
2
[[0.02027544 0.02195464 0.02561902]]
2
[[0.02013247 0.02200992 0.02550812]]
2
[[0.02000372 0.02205969 0.0253862 ]]
2
[[0.0198878  0.02210451 0.02525446]]
2
[[0.01978341 0.02214486 0.02511398]]
0
[[0.02017992 0.0221812  0.02498749]]
0
[[0.0209574  0.02221392 0.02487359]]
2
[[0.02165748 0.02224339 0.02474947]]
0
[[0.02250683 0.02226992 0.0246377 ]]
2
[[0.02327163 0.0222938  0.02451569]]
1
[[0.02396029 0.02247871 0.02440582]]
2
[[0.0245804  0.02264521 0.0242857 ]]
0
[[0.02499191 0.02279513 0.02417753]]
0
[[0.02521343 0.02293013 0.02408013]]
0
[[0.02526282 0.02305169 0.02399243]]
2
[[0.0253073  0.02316115 0.02391359]]
0
[[0.02519692 0.02325971 0.02384259]]
0
[[0.024948   0.02334846 0.02377867]]
0
[[0.02457604 0.02342837 0.0237211 ]]
1
[[0.02424111 0.02348696 0.02366927]]
0
[[0.02379597 0.02353972 0

[[0.00780242 0.00761331 0.00796802]]
2
[[0.00774386 0.00746153 0.00792331]]
2
[[0.00769112 0.00732485 0.00787583]]
2
[[0.00764363 0.00720178 0.00782588]]
2
[[0.00760087 0.00709097 0.00777377]]
2
[[0.00756237 0.00699118 0.00771975]]
2
[[0.0075277  0.00690133 0.00753023]]
2
[[0.00749648 0.00682042 0.00735271]]
2
[[0.00746837 0.00674757 0.00718864]]
2
[[0.00744306 0.00668197 0.00703919]]
0
[[0.00737349 0.0066229  0.00690462]]
0
[[0.00726448 0.00656971 0.00678344]]
2
[[0.00716632 0.00652181 0.00667648]]
0
[[0.00703284 0.00647869 0.00658017]]
2
[[0.00691265 0.00643985 0.0064953 ]]
1
[[0.00680443 0.00642763 0.00641888]]
2
[[0.00670697 0.00641662 0.0063509 ]]
0
[[0.00657694 0.00640671 0.00628969]]
0
[[0.00641837 0.00639779 0.00623457]]
0
[[0.00623508 0.00638975 0.00618493]]
2
[[0.00607005 0.00638252 0.00613813]]
0
[[0.0059206  0.006376   0.00609599]]
0
[[0.0058033  0.00637013 0.00605805]]
0
[[0.00572909 0.00636485 0.00602388]]
1
[[0.00566226 0.00630293 0.00599311]]
0
[[0.0056433  0.00624717 0

[[0.00230777 0.0021955  0.00233947]]
2
[[0.00231285 0.00218219 0.0023267 ]]
2
[[0.00231743 0.0021702  0.00231284]]
2
[[0.00232156 0.0021594  0.00229811]]
2
[[0.00232527 0.00214968 0.00228297]]
2
[[0.00232862 0.00214092 0.00226784]]
2
[[0.00233163 0.00213304 0.00225308]]
2
[[0.00233434 0.00212594 0.00223903]]
0
[[0.00232051 0.00211955 0.00222637]]
0
[[0.00229188 0.00211379 0.00221497]]
0
[[0.00225012 0.00210861 0.0022047 ]]
0
[[0.0021968  0.00210394 0.00219546]]
0
[[0.00213346 0.00209974 0.00218714]]
2
[[0.00207642 0.00209596 0.00217742]]
1
[[0.00202506 0.00208711 0.00216867]]
2
[[0.00197882 0.00207914 0.00215858]]
0
[[0.00194722 0.00207197 0.00214949]]
0
[[0.00193205 0.00206551 0.00214131]]
0
[[0.0019327  0.00205969 0.00213394]]
2
[[0.00193328 0.00205445 0.00212513]]
0
[[0.00194581 0.00204974 0.00211719]]
0
[[0.00196628 0.00204549 0.00211005]]
0
[[0.00199008 0.00204166 0.00210361]]
1
[[0.00201152 0.0020296  0.00209782]]
0
[[0.00202821 0.00201874 0.0020926 ]]
1
[[0.00204324 0.00200282 0

[[0.00138592 0.00130332 0.00131694]]
2
[[0.00139604 0.00129989 0.00131348]]
2
[[0.00140514 0.00129681 0.00131066]]
2
[[0.00141334 0.00129403 0.00130866]]
2
[[0.00142072 0.00129153 0.00130763]]
2
[[0.00142737 0.00128927 0.00130764]]
2
[[0.00143336 0.00128725 0.00130875]]
2
[[0.00143875 0.00128542 0.00131094]]
0
[[0.00143247 0.00128378 0.00131291]]
0
[[0.00141573 0.0012823  0.00131468]]
0
[[0.00138969 0.00128096 0.00131628]]
0
[[0.00135547 0.00127976 0.00131772]]
0
[[0.00131416 0.00127868 0.00131901]]
2
[[0.00127695 0.00127771 0.00131869]]
2
[[0.00124345 0.00127683 0.00131691]]
2
[[0.00121328 0.00127604 0.00131381]]
0
[[0.00119153 0.00127533 0.00131102]]
1
[[0.00117195 0.0012681  0.00130851]]
2
[[0.00115431 0.00126159 0.00130476]]
2
[[0.00113843 0.00125572 0.00129991]]
0
[[0.00113915 0.00125044 0.00129555]]
0
[[0.00115407 0.00124568 0.00129161]]
0
[[0.00117887 0.0012414  0.00128807]]
1
[[0.00120121 0.00123362 0.00128488]]
0
[[0.00122435 0.00122661 0.00128201]]
1
[[0.00124518 0.00121837 0

[[0.00044829 0.00047688 0.00050727]]
2
[[0.00044645 0.00047042 0.00050191]]
2
[[0.0004448  0.0004646  0.00049646]]
2
[[0.00044331 0.00045936 0.00049093]]
2
[[0.00044196 0.00045464 0.00048534]]
2
[[0.00044075 0.00045039 0.0004797 ]]
2
[[0.00043967 0.00044657 0.00047402]]
0
[[0.00044052 0.00044312 0.0004689 ]]
0
[[0.00044213 0.00044002 0.00046429]]
0
[[0.0004434  0.00043722 0.00046015]]
0
[[0.00044347 0.00043471 0.00045641]]
0
[[0.00044183 0.00043244 0.00045305]]
2
[[0.00044035 0.0004304  0.00044945]]
2
[[0.00043902 0.00042857 0.00044564]]
2
[[0.00043783 0.00042691 0.00044166]]
0
[[0.0004336  0.00042543 0.00043807]]
1
[[0.00042979 0.00042181 0.00043484]]
2
[[0.00042636 0.00041856 0.00043138]]
2
[[0.00042328 0.00041563 0.00042772]]
2
[[0.0004205  0.000413   0.00042389]]
2
[[0.000418   0.00041062 0.00041991]]
2
[[0.00041574 0.00040848 0.00041579]]
2
[[0.00041371 0.00040656 0.00041156]]
2
[[0.00041189 0.00040483 0.00040728]]
2
[[0.00041024 0.00040326 0.00040302]]
1
[[0.00040876 0.00039853 0

[[0.00011421 0.00011248 0.00011876]]
2
[[0.00011495 0.00011008 0.00011771]]
2
[[0.00011562 0.00010791 0.00011661]]
2
[[0.00011622 0.00010596 0.00011546]]
2
[[0.00011677 0.00010421 0.00011428]]
2
[[0.00011726 0.00010263 0.00011312]]
2
[[0.0001177  0.00010121 0.00011204]]
0
[[1.1697037e-04 9.9927631e-05 1.1105521e-04]]
0
[[1.15199262e-04 9.87745152e-05 1.10172936e-04]]
0
[[1.12503920e-04 9.77361924e-05 1.09378496e-04]]
0
[[1.09001565e-04 9.68012318e-05 1.08663138e-04]]
0
[[1.0480549e-04 9.5959345e-05 1.0801900e-04]]
2
[[1.0102714e-04 9.5201271e-05 1.0728829e-04]]
2
[[9.7624914e-05 9.4518662e-05 1.0648058e-04]]
2
[[9.4561387e-05 9.3904011e-05 1.0560459e-04]]
0
[[9.290726e-05 9.335054e-05 1.048158e-04]]
1
[[9.1417802e-05 9.4547693e-05 1.0410554e-04]]
2
[[9.0076617e-05 9.5625663e-05 1.0332039e-04]]
2
[[8.8868946e-05 9.6596326e-05 1.0246883e-04]]
2
[[8.7781504e-05 9.7470358e-05 1.0155860e-04]]
2
[[8.6802313e-05 9.8257377e-05 1.0059674e-04]]
2
[[8.592060e-05 9.896605e-05 9.958967e-05]]
2
[[8.

[[0.02511459 0.01997257 0.02596693]]
2
[[0.02615146 0.01985366 0.0262031 ]]
2
[[0.02708511 0.01974658 0.02637751]]
2
[[0.02792582 0.01965016 0.02651567]]
0
[[0.02840869 0.01956334 0.02664008]]
1
[[0.02884348 0.0210089  0.0267521 ]]
2
[[0.029235   0.02231054 0.02687195]]
2
[[0.02958754 0.02348261 0.02700624]]
2
[[0.02990498 0.024538   0.02715941]]
2
[[0.03019083 0.02548833 0.02733394]]
2
[[0.03044822 0.02634405 0.02753055]]
2
[[0.03067998 0.02711459 0.02774847]]
2
[[0.03088867 0.02780841 0.02798565]]
2
[[0.03107659 0.02843317 0.02823905]]
0
[[0.03094293 0.02899574 0.02846723]]
2
[[0.03082258 0.02950229 0.02869995]]
1
[[0.0307142  0.0299131  0.02890951]]
1
[[0.03061662 0.03013206 0.0290982 ]]
2
[[0.03052875 0.03032923 0.02926774]]
0
[[0.03015378 0.03050677 0.02942041]]
1
[[0.02981613 0.03035436 0.02955787]]
0
[[0.02932273 0.03021712 0.02968166]]
2
[[0.02887844 0.03009354 0.03005769]]
2
[[0.02847839 0.02998227 0.03078803]]
0
[[0.02826796 0.02988207 0.03144566]]
2
[[0.02807848 0.02979185 0

2
[[0.04230083 0.0403392  0.04574981]]
1
[[0.04214844 0.04106459 0.04618167]]
2
Buy: Rs.0.50
[[0.04201122 0.04171776 0.04679082]]
2
[[0.04188766 0.04230592 0.04727188]]
0
[[0.04222786 0.04283552 0.04770506]]
1
[[0.0425342  0.04374446 0.04809511]]
2
[[0.04281004 0.04456291 0.04837697]]
2
[[0.04305842 0.04529989 0.048561  ]]
2
[[0.04328208 0.0459635  0.04865669]]
2
[[0.04348347 0.04656105 0.04867268]]
2
[[0.04366481 0.04709912 0.0486169 ]]
2
[[0.0438281  0.04758362 0.04849656]]
2
[[0.04397513 0.04801989 0.04831826]]
2
[[0.04410753 0.04841273 0.04808802]]
0
[[0.04450752 0.04876646 0.0478807 ]]
2
[[0.04486769 0.04908497 0.04764919]]
1
[[0.04519201 0.04893942 0.04744072]]
1
[[0.04548405 0.04838478 0.04725301]]
2
[[0.04574701 0.04788536 0.04704675]]
0
[[0.04594549 0.04743565 0.04686103]]
1
[[0.04612421 0.04662525 0.04669379]]
0
[[0.04602117 0.04589553 0.04654321]]
2
[[0.04592839 0.04523845 0.04662981]]
2
[[0.04584485 0.04464678 0.04707133]]
0
[[0.04560152 0.04411401 0.04746889]]
2
[[0.045382

[[0.05015957 0.04746145 0.0520351 ]]
2
[[0.05014228 0.0474529  0.05235904]]
1
[[0.05012671 0.04776346 0.05265073]]
2
[[0.05011269 0.0480431  0.05311634]]
1
[[0.05010007 0.04862813 0.05353561]]
2
[[0.0500887  0.04915493 0.05383904]]
2
[[0.05007847 0.04962928 0.05403775]]
2
[[0.05006925 0.05005641 0.05414192]]
2
[[0.05006095 0.05044102 0.0541608 ]]
1
[[0.05005348 0.05092727 0.05417781]]
2
[[0.05004675 0.05136511 0.05473284]]
2
[[0.0500407  0.05175937 0.05515781]]
2
[[0.05003524 0.05211438 0.05546508]]
2
[[0.05003033 0.05243405 0.05566598]]
2
[[0.05002591 0.05272189 0.05577083]]
0
[[0.05045404 0.05298108 0.05586523]]
2
[[0.05083956 0.05321447 0.05587389]]
1
[[0.0511867  0.05340593 0.05588169]]
1
[[0.05149928 0.05353399 0.05588871]]
2
[[0.05178074 0.0536493  0.05581858]]
0
[[0.05221615 0.05375313 0.05575543]]
1
[[0.05260822 0.05373709 0.05569856]]
0
[[0.05300594 0.05372265 0.05564736]]
2
[[0.05336406 0.05370964 0.05579881]]
2
[[0.05368653 0.05369793 0.05626681]]
0
[[0.05394272 0.05368739 0

[[0.07213287 0.07218643 0.07585742]]
2
[[0.07215815 0.07214092 0.07601955]]
1
[[0.07218091 0.07211163 0.07616554]]
2
[[0.07220141 0.07208525 0.076451  ]]
1
[[0.07221986 0.07214332 0.07670803]]
2
[[0.07223649 0.0721956  0.07684384]]
2
[[0.07225145 0.07224268 0.07687036]]
2
[[0.07226492 0.07228508 0.07679848]]
2
[[0.07227706 0.07232326 0.07663811]]
1
[[0.07228798 0.07243051 0.07649371]]
2
[[0.07229782 0.0725271  0.07682583]]
2
[[0.07230668 0.07261407 0.07702997]]
1
[[0.07231466 0.07277764 0.07721379]]
1
[[0.07232184 0.07301184 0.07737932]]
2
[[0.07232831 0.07322273 0.07743274]]
2
[[0.07233413 0.07341262 0.07738519]]
2
[[0.07233938 0.07358361 0.07724681]]
2
[[0.0723441  0.07373758 0.07702687]]
1
[[0.07234836 0.07379104 0.07682882]]
2
[[0.07235219 0.07383919 0.07655561]]
0
[[0.0724154  0.07388254 0.07630961]]
1
[[0.07247231 0.07371135 0.07608809]]
0
[[0.07249352 0.07355721 0.07588863]]
2
[[0.07251262 0.07341841 0.07586274]]
2
[[0.07252982 0.07329343 0.07611581]]
0
[[0.07251025 0.07318088 0

[[0.06623013 0.06882575 0.06836777]]
2
[[0.06614514 0.06813068 0.06857192]]
1
[[0.0660686  0.06711105 0.06875575]]
2
[[0.06599969 0.06619292 0.06884206]]
2
[[0.06593764 0.0653662  0.06884049]]
2
[[0.06588176 0.06462178 0.06875978]]
2
[[0.06583145 0.06395146 0.06860793]]
1
[[0.06578614 0.06351252 0.06847119]]
2
[[0.06574535 0.06311728 0.06878498]]
2
[[0.06570861 0.06276139 0.06898887]]
1
[[0.06567554 0.06281237 0.06917247]]
1
[[0.06564575 0.06324095 0.06933779]]
2
[[0.06561893 0.06362687 0.06940731]]
2
[[0.06559478 0.06397437 0.06939049]]
2
[[0.06557304 0.06428727 0.06929596]]
2
[[0.06555346 0.06456902 0.06913157]]
2
[[0.06553583 0.06482273 0.06890447]]
2
[[0.06551995 0.06505118 0.06862116]]
2
[[0.06550565 0.06525689 0.06828757]]
2
[[0.06549278 0.06544212 0.06790907]]
2
[[0.06548119 0.0656089  0.06749057]]
2
[[0.06547075 0.06575909 0.06703652]]
2
[[0.06546135 0.06589433 0.06655098]]
0
[[0.06506212 0.0660161  0.06611378]]
2
[[0.06470263 0.06612575 0.06564441]]
2
[[0.06437892 0.06622449 0

[[0.0452929  0.04730484 0.04618014]]
2
[[0.04527869 0.04692427 0.04647169]]
1
[[0.04526591 0.04629626 0.04673421]]
2
[[0.04525439 0.04573076 0.0469186 ]]
2
[[0.04524402 0.04522156 0.04703243]]
2
[[0.04523469 0.04476305 0.04708258]]
2
[[0.04522628 0.04435019 0.04707532]]
1
[[0.04521871 0.04402396 0.04706878]]
2
[[0.04521189 0.04373021 0.04750746]]
2
[[0.04520575 0.0434657  0.04784998]]
1
[[0.04520022 0.04347188 0.04815841]]
1
[[0.04519525 0.04375521 0.04843614]]
2
[[0.04519077 0.04401035 0.04863265]]
2
[[0.04518673 0.04424008 0.04875582]]
2
[[0.0451831  0.04444695 0.04881278]]
2
[[0.04517983 0.04463322 0.04881008]]
2
[[0.04517688 0.04480095 0.04875362]]
2
[[0.04517423 0.04495198 0.04864882]]
2
[[0.04517184 0.04508797 0.04850059]]
2
[[0.04516969 0.04521043 0.04831341]]
2
[[0.04516776 0.0453207  0.04809134]]
2
[[0.04516601 0.04541999 0.04783809]]
2
[[0.04516444 0.0455094  0.04755703]]
0
[[0.0451658  0.0455899  0.04730394]]
2
[[0.04516702 0.04566239 0.04702358]]
2
[[0.04516812 0.04572767 0

[[0.02629954 0.0255411  0.02689034]]
2
[[0.02623633 0.02559499 0.02673543]]
1
[[0.02617942 0.02561804 0.02659595]]
2
[[0.02612817 0.02563878 0.02644034]]
2
[[0.02608202 0.02565747 0.02627039]]
2
[[0.02604046 0.02567429 0.02608769]]
2
Buy: Rs.0.47
[[0.02600304 0.02568944 0.02589371]]
2
[[0.02596935 0.02570308 0.02569212]]
1
[[0.02593901 0.02558111 0.02551061]]
2
[[0.02591169 0.02547129 0.02583286]]
2
[[0.02588709 0.0253724  0.02609579]]
1
[[0.02586494 0.02520768 0.02633256]]
1
[[0.025845   0.02503438 0.02654575]]
2
[[0.02582704 0.02487833 0.02670797]]
2
[[0.02581087 0.02473782 0.02682409]]
2
[[0.0257963  0.0246113  0.02689858]]
2
[[0.02578319 0.02449737 0.02693546]]
2
[[0.02577138 0.02439478 0.02693844]]
2
[[0.02576075 0.02430241 0.02691087]]
2
[[0.02575118 0.02421923 0.02685582]]
2
[[0.02574256 0.02414433 0.02677607]]
2
[[0.0257348  0.02407689 0.02667415]]
2
[[0.02572781 0.02401616 0.02655237]]
2
[[0.02572151 0.02396148 0.02641283]]
0
[[0.0255872  0.02391224 0.02628719]]
2
[[0.02546627

[[0.07209975 0.07024192 0.07841813]]
0
[[0.07286479 0.07075782 0.07835741]]
1
[[0.07355366 0.07163958 0.07830273]]
2
[[0.07417396 0.07243357 0.07820431]]
1
[[0.0747325  0.07335956 0.07811569]]
2
[[0.07523545 0.07419337 0.07798679]]
2
[[0.07568832 0.07494417 0.07782169]]
2
[[0.07609612 0.07562023 0.07762407]]
2
[[0.07646331 0.07622898 0.07739729]]
1
[[0.07679395 0.07646643 0.07719308]]
2
[[0.07709168 0.07668025 0.07804585]]
1
[[0.07735977 0.0765836  0.07881373]]
0
[[0.07725921 0.07649657 0.07950517]]
2
[[0.07716867 0.07641821 0.08087402]]
2
[[0.07708713 0.07634764 0.08205961]]
2
[[0.07701372 0.0762841  0.08307949]]
2
[[0.07694761 0.07622689 0.08394957]]
2
[[0.07688809 0.07617537 0.08468425]]
2
[[0.07683449 0.07612898 0.08529658]]
2
[[0.07678623 0.07608721 0.08579837]]
2
[[0.07674277 0.0760496  0.08620033]]
2
[[0.07670364 0.07601573 0.08651216]]
2
[[0.0766684  0.07598523 0.08674263]]
2
[[0.07663667 0.07595777 0.08689971]]
2
[[0.0766081  0.07593304 0.0869906 ]]
2
[[0.07658237 0.07591077 0

[[0.11217064 0.10761056 0.11637701]]
1
[[0.11225021 0.1082354  0.11625635]]
2
[[0.11232185 0.10879804 0.11609605]]
1
[[0.11238637 0.10945877 0.11595171]]
2
[[0.11244446 0.11005372 0.11577018]]
2
[[0.11249676 0.11058944 0.11555523]]
2
[[0.11254387 0.11107184 0.11531027]]
2
[[0.11258627 0.11150621 0.11503837]]
1
[[0.11262447 0.11166636 0.11479355]]
2
[[0.11265885 0.11181056 0.11530988]]
1
[[0.11268982 0.11170571 0.11577481]]
0
[[0.11237463 0.1116113  0.11619346]]
2
[[0.11209081 0.11152628 0.11711381]]
2
[[0.11183525 0.11144973 0.11789232]]
2
[[0.11160513 0.11138079 0.11854279]]
2
[[0.11139792 0.11131872 0.11907767]]
2
[[0.11121134 0.11126284 0.11950822]]
2
[[0.11104333 0.11121251 0.11984465]]
0
[[0.11124825 0.11116719 0.12014759]]
2
[[0.11143278 0.11112639 0.12036881]]
0
[[0.11196467 0.11108964 0.12056801]]
2
[[0.1124436  0.11105655 0.12069559]]
2
[[0.11287486 0.11102676 0.12075863]]
2
[[0.11326318 0.11099993 0.12076352]]
2
[[0.11361285 0.11097577 0.12071602]]
0
[[0.11406185 0.11095402 0

0
[[0.13025372 0.12833676 0.13591939]]
1
[[0.13027613 0.12870911 0.13576967]]
2
[[0.1302963  0.1290444  0.13558379]]
1
[[0.13031447 0.12932168 0.13541642]]
2
[[0.13033083 0.12957136 0.13521473]]
2
[[0.13034557 0.12979619 0.13498221]]
2
[[0.13035883 0.12999864 0.13472201]]
2
[[0.13037078 0.13018093 0.13443696]]
1
[[0.13038154 0.13009164 0.13418029]]
2
[[0.13039123 0.13001125 0.13457009]]
1
[[0.13039994 0.12971683 0.13492109]]
0
[[0.13012785 0.12945172 0.13523714]]
2
[[0.12988283 0.129213   0.13598235]]
2
[[0.1296622  0.12899806 0.13660342]]
2
[[0.12946354 0.1288045  0.13711247]]
2
[[0.12928465 0.12863022 0.13752046]]
2
[[0.12912357 0.12847328 0.13783729]]
2
[[0.12897854 0.12833197 0.13807192]]
0
[[0.12912385 0.12820473 0.1382832 ]]
2
[[0.1292547  0.12809016 0.13842256]]
0
[[0.1296538  0.12798698 0.13854806]]
2
[[0.13001317 0.12789409 0.13861008]]
2
[[0.13033676 0.12781043 0.1386149 ]]
1
[[0.13062814 0.12813187 0.13861923]]
2
[[0.1308905  0.1284213  0.13857207]]
2
[[0.13112676 0.12868193

[[0.13502899 0.1337079  0.14074162]]
2
[[0.13502742 0.13380842 0.14045689]]
2
[[0.13502601 0.13389893 0.14015289]]
2
[[0.13502474 0.13398044 0.13983162]]
2
[[0.1350236  0.13405383 0.13949488]]
2
[[0.13502257 0.13411991 0.13914433]]
1
[[0.13502164 0.13397603 0.13882868]]
2
[[0.1350208  0.13384646 0.13910484]]
1
[[0.13502005 0.13355164 0.13935351]]
0
[[0.13468064 0.13328616 0.13957743]]
2
[[0.13437504 0.13304712 0.14019604]]
2
[[0.13409984 0.13283187 0.14070642]]
2
[[0.13385205 0.13263805 0.14111915]]
2
[[0.13362892 0.13246353 0.14144382]]
2
[[0.133428   0.13230638 0.14168906]]
2
[[0.13324709 0.13216488 0.1418627 ]]
0
[[0.13328058 0.13203746 0.14201906]]
2
[[0.13331074 0.13192272 0.14211252]]
0
[[0.13355596 0.13181941 0.14219667]]
2
[[0.13377678 0.13172638 0.14222501]]
2
[[0.13397563 0.13164261 0.14220308]]
1
[[0.13415466 0.13193028 0.14218333]]
2
[[0.13431588 0.1321893  0.14211808]]
2
[[0.13446105 0.13242255 0.14201187]]
2
[[0.13459176 0.13263258 0.14186877]]
2
[[0.13470946 0.13282171 0

[[0.12174674 0.12441585 0.12676893]]
2
[[0.12165707 0.12427343 0.1264409 ]]
2
[[0.12157633 0.12414518 0.12610447]]
2
[[0.12150363 0.1240297  0.12576059]]
2
[[0.12143816 0.12392572 0.12541008]]
2
[[0.12137921 0.12383209 0.1250537 ]]
2
[[0.12132613 0.12374778 0.12469214]]
2
[[0.12127834 0.12367187 0.12478095]]
2
[[0.1212353  0.12360351 0.12482063]]
2
[[0.12119655 0.12354195 0.12481603]]
2
[[0.12116165 0.12348653 0.12477156]]
2
[[0.12113024 0.12343661 0.12469117]]
2
[[0.12110195 0.12339167 0.12457847]]
0
[[0.12070952 0.12335121 0.12447698]]
2
[[0.12035615 0.12331477 0.12434531]]
0
[[0.11974318 0.12328196 0.12422675]]
2
[[0.11919122 0.12325241 0.12407974]]
2
[[0.11869422 0.12322581 0.12390716]]
1
[[0.11824669 0.12260549 0.12375177]]
2
[[0.11784371 0.12204692 0.12357169]]
2
[[0.11748085 0.12154396 0.12336945]]
2
[[0.11715411 0.12109107 0.12314729]]
2
[[0.11685991 0.12068326 0.12290726]]
2
[[0.11659499 0.12031605 0.12265119]]
2
[[0.11635643 0.11998539 0.12238076]]
0
[[0.11612898 0.11968765 0

[[0.07288507 0.07313931 0.07624464]]
2
[[0.07273866 0.07303409 0.07601059]]
2
[[0.07260683 0.07293934 0.0757729 ]]
2
[[0.07248813 0.07285402 0.07553201]]
2
[[0.07238124 0.0727772  0.0752883 ]]
2
[[0.072285   0.07270803 0.07504214]]
2
[[0.07219833 0.07264574 0.07479383]]
2
[[0.07212029 0.07258965 0.07454368]]
2
[[0.07205003 0.07253915 0.07429194]]
2
[[0.07198675 0.07249367 0.07403884]]
1
[[0.07192978 0.07221995 0.07381094]]
1
[[0.07187847 0.07174785 0.07360573]]
2
[[0.07183228 0.07132276 0.07339474]]
2
[[0.07179068 0.07093999 0.0731786 ]]
2
[[0.07175323 0.07059532 0.07295789]]
2
[[0.0717195  0.07028496 0.07273314]]
0
[[0.07133017 0.0700055  0.07253076]]
2
[[0.07097961 0.06975386 0.07232264]]
2
[[0.07066394 0.06952727 0.07210942]]
1
[[0.0703797  0.06921271 0.07191741]]
2
[[0.07012375 0.06892947 0.07171882]]
2
[[0.06989329 0.06867443 0.07151435]]
2
[[0.06968576 0.06844477 0.07130464]]
2
[[0.0694989  0.06823798 0.07109029]]
2
[[0.06933063 0.06805178 0.07087182]]
2
[[0.06917912 0.06788411 0

[[0.03767528 0.03898773 0.03986392]]
2
[[0.03756971 0.03895262 0.03972145]]
2
[[0.03747464 0.03892101 0.03957756]]
2
[[0.03738904 0.03889254 0.03943245]]
2
[[0.03731196 0.0388669  0.03928629]]
2
[[0.03724256 0.03884382 0.03913922]]
2
[[0.03718006 0.03882304 0.03899139]]
2
[[0.03712379 0.03880432 0.03884293]]
1
[[0.03707311 0.03856699 0.03870925]]
1
[[0.03702749 0.03814635 0.03858888]]
2
[[0.0369864  0.03776759 0.03846527]]
2
[[0.0369494  0.03742652 0.0383388 ]]
2
[[0.03691609 0.03711941 0.03820979]]
2
[[0.0368861  0.03684288 0.03807853]]
2
[[0.03685908 0.03659387 0.0379453 ]]
2
[[0.03683476 0.03636966 0.03781034]]
0
[[0.03668012 0.03616776 0.03768881]]
0
[[0.03641394 0.03598596 0.03757938]]
2
[[0.03617426 0.03582226 0.03746596]]
2
[[0.03595845 0.03567486 0.037349  ]]
2
[[0.03576411 0.03554213 0.03722889]]
2
[[0.03558913 0.03542262 0.03710598]]
2
[[0.03543156 0.035315   0.03698058]]
2
[[0.03528968 0.03521809 0.036853  ]]
0
[[0.03512127 0.03513083 0.03673812]]
2
[[0.03496963 0.03505226 0

[[0.0180638  0.01813588 0.0186492 ]]
2
[[0.01803454 0.01811329 0.01857013]]
2
[[0.01800819 0.01809295 0.01849083]]
2
[[0.01798446 0.01807464 0.01841136]]
2
[[0.0179631  0.01805815 0.01833177]]
2
[[0.01794386 0.0180433  0.0182521 ]]
2
[[0.01792654 0.01802993 0.01817239]]
1
[[0.01791094 0.01792071 0.01810061]]
1
[[0.0178969  0.01773041 0.01803598]]
2
[[0.01788425 0.01755906 0.01796989]]
2
[[0.01787286 0.01740477 0.01790252]]
2
[[0.01786261 0.01726583 0.01783401]]
2
[[0.01785338 0.01714073 0.01776475]]
2
[[0.01784506 0.01702808 0.01769534]]
2
[[0.01783757 0.01692665 0.01762632]]
0
[[0.01768892 0.01683531 0.01756417]]
0
[[0.01741453 0.01675306 0.01750821]]
2
[[0.01716745 0.01667901 0.01745014]]
2
[[0.01694497 0.01661232 0.01739017]]
2
[[0.01674464 0.01655228 0.01732853]]
2
[[0.01656425 0.01649821 0.0172654 ]]
2
[[0.01640182 0.01644952 0.01720096]]
2
[[0.01625556 0.01640568 0.01713536]]
2
[[0.01612386 0.01636621 0.01706875]]
2
[[0.01600527 0.01633066 0.01700124]]
2
[[0.01589849 0.01629866 0

[[0.00756565 0.00807413 0.00800031]]
2
[[0.00754089 0.00806968 0.0079652 ]]
2
[[0.0075186  0.00806568 0.00793068]]
2
[[0.00749852 0.00806207 0.007897  ]]
2
[[0.00748044 0.00805882 0.00786436]]
1
[[0.00746416 0.00799932 0.00783497]]
1
[[0.00744951 0.00788957 0.00780851]]
2
[[0.00743631 0.00779075 0.00778164]]
2
[[0.00742442 0.00770177 0.00775374]]
2
[[0.00741372 0.00762164 0.00772485]]
2
[[0.00740409 0.00754949 0.00769508]]
2
[[0.00739541 0.00748453 0.00766452]]
2
[[0.0073876  0.00742603 0.00763328]]
0
[[0.00735663 0.00737335 0.00760515]]
0
[[0.00730554 0.00732592 0.00757981]]
2
[[0.00725954 0.00728321 0.0075533 ]]
2
[[0.00721813 0.00724475 0.00752575]]
2
[[0.00718083 0.00721012 0.00749726]]
2
[[0.00714725 0.00717894 0.00746795]]
2
[[0.00711701 0.00715086 0.00743791]]
2
[[0.00708978 0.00712558 0.00740722]]
2
[[0.00706526 0.00710281 0.00737596]]
2
[[0.00704318 0.00708231 0.0073442 ]]
2
[[0.0070233  0.00706385 0.00731201]]
2
[[0.0070054  0.00704723 0.00727944]]
2
[[0.00698928 0.00703227 0

[[0.00315431 0.00327973 0.00331768]]
2
[[0.00314698 0.00325718 0.00330166]]
2
[[0.00314038 0.00323688 0.00328547]]
0
[[0.00313071 0.00321859 0.00327088]]
2
[[0.00312201 0.00320213 0.00325599]]
2
[[0.00311417 0.00318731 0.00324082]]
2
[[0.00310711 0.00317396 0.00322542]]
2
[[0.00310075 0.00316194 0.00320981]]
2
[[0.00309502 0.00315112 0.00319402]]
2
[[0.00308987 0.00314137 0.00317808]]
2
[[0.00308523 0.0031326  0.003162  ]]
2
[[0.00308105 0.0031247  0.00314582]]
2
[[0.00307728 0.00311758 0.00312955]]
0
[[0.00305354 0.00311118 0.00311489]]
0
[[0.00301371 0.00310541 0.0031017 ]]
2
[[0.00297785 0.00310021 0.00308818]]
2
[[0.00294555 0.00309554 0.00307445]]
2
[[0.00291648 0.00309132 0.00306064]]
2
[[0.00289029 0.00308753 0.00304686]]
2
[[0.00286671 0.00308412 0.00303322]]
2
[[0.00284548 0.00308104 0.00301981]]
2
[[0.00282637 0.00307827 0.00300673]]
2
[[0.00280915 0.00307578 0.00299406]]
2
[[0.00279365 0.00307353 0.00298186]]
2
[[0.0027797  0.00307151 0.00297021]]
2
[[0.00276713 0.00306969 0

[[0.00128941 0.00132988 0.00137143]]
2
[[0.00128529 0.00132779 0.00136354]]
1
[[0.00128158 0.0013203  0.00135643]]
2
[[0.00127823 0.00131356 0.00134922]]
2
[[0.00127522 0.00130749 0.00134193]]
0
[[0.00127243 0.00130202 0.00133536]]
2
[[0.00126991 0.0012971  0.00132864]]
2
[[0.00126764 0.00129267 0.0013218 ]]
2
[[0.0012656  0.00128868 0.00131484]]
2
[[0.00126377 0.00128508 0.00130779]]
1
[[0.00126211 0.00127445 0.00130145]]
1
[[0.00126062 0.00125827 0.00129573]]
2
[[0.00125928 0.0012437  0.00128981]]
2
[[0.00125807 0.00123058 0.0012837 ]]
2
[[0.00125698 0.00121877 0.00127743]]
2
[[0.001256   0.00120813 0.00127101]]
0
[[0.00124459 0.00119856 0.00126523]]
2
[[0.00123431 0.00118993 0.00125927]]
2
[[0.00122505 0.00118217 0.00125314]]
2
[[0.00121671 0.00117517 0.00124687]]
2
[[0.00120921 0.00116888 0.00124047]]
2
[[0.00120245 0.00116321 0.00123396]]
2
[[0.00119636 0.0011581  0.00122735]]
2
[[0.00119088 0.00115351 0.00122066]]
2
[[0.00118595 0.00114937 0.0012139 ]]
2
[[0.0011815  0.00114564 0

[[0.0005066  0.00050721 0.00052953]]
1
[[0.00050404 0.00050542 0.00052659]]
2
[[0.00050173 0.00050382 0.00052359]]
2
[[0.00049965 0.00050237 0.00052055]]
0
[[0.00049654 0.00050107 0.0005178 ]]
2
[[0.00049375 0.0004999  0.00051499]]
2
[[0.00049123 0.00049884 0.00051211]]
2
[[0.00048897 0.00049789 0.00050918]]
2
[[0.00048693 0.00049704 0.0005062 ]]
1
[[0.00048509 0.00049316 0.00050352]]
1
[[0.00048344 0.00048681 0.0005011 ]]
2
[[0.00048195 0.00048109 0.00049859]]
2
[[0.0004806  0.00047595 0.000496  ]]
2
[[0.0004794  0.00047131 0.00049334]]
2
[[0.00047831 0.00046714 0.00049061]]
2
[[0.00047733 0.00046338 0.00048782]]
2
[[0.00047645 0.00046    0.00048499]]
2
[[0.00047565 0.00045695 0.00048212]]
2
[[0.00047494 0.00045421 0.0004792 ]]
2
[[0.0004743  0.00045174 0.00047626]]
0
[[0.00046844 0.00044952 0.00047361]]
2
[[0.00046316 0.00044751 0.00047091]]
2
[[0.00045841 0.00044571 0.00046816]]
2
[[0.00045413 0.00044409 0.00046537]]
2
[[0.00045028 0.00044262 0.00046254]]
2
[[0.00044681 0.00044131 0

[[0.00014141 0.00014755 0.00015394]]
2
[[0.00013997 0.00014711 0.00015303]]
2
[[0.00013867 0.00014672 0.00015211]]
0
[[0.00013905 0.00014636 0.00015127]]
2
[[0.0001394  0.00014604 0.00015041]]
2
[[0.00013971 0.00014576 0.00014952]]
2
[[0.00013999 0.0001455  0.00014861]]
2
[[0.00014024 0.00014526 0.00014768]]
1
[[0.00014046 0.00014399 0.00014684]]
1
[[0.00014067 0.00014188 0.00014609]]
2
[[0.00014085 0.00013998 0.0001453 ]]
2
[[0.00014101 0.00013828 0.00014448]]
2
[[0.00014116 0.00013674 0.00014364]]
2
[[0.0001413  0.00013535 0.00014277]]
2
[[0.00014142 0.0001341  0.00014189]]
2
[[0.00014153 0.00013298 0.00014099]]
2
[[0.00014162 0.00013197 0.00014008]]
2
[[0.00014171 0.00013106 0.00013918]]
2
[[0.00014179 0.00013024 0.0001383 ]]
0
[[0.00013996 0.0001295  0.00013751]]
2
[[0.00013831 0.00012883 0.00013673]]
2
[[0.00013682 0.00012823 0.00013594]]
0
[[0.00013365 0.00012769 0.00013524]]
2
[[0.00013079 0.00012721 0.0001345 ]]
2
[[0.00012821 0.00012677 0.00013374]]
2
[[0.00012589 0.00012638 0

[[4.8732742e-05 5.1770894e-05 5.2720377e-05]]
2
[[4.8946993e-05 5.1934625e-05 5.2387801e-05]]
2
[[4.9139915e-05 5.2082058e-05 5.2045965e-05]]
2
[[4.9313632e-05 5.2214811e-05 5.1696603e-05]]
1
[[4.9470054e-05 5.1723408e-05 5.1382020e-05]]
1
[[4.9610906e-05 5.0675426e-05 5.1098752e-05]]
2
[[4.9737737e-05 4.9731771e-05 5.0802279e-05]]
2
[[4.985194e-05 4.888206e-05 5.049413e-05]]
2
[[4.9954775e-05 4.8116934e-05 5.0175702e-05]]
2
[[5.0047372e-05 4.7427977e-05 4.9848255e-05]]
2
[[5.0130751e-05 4.6807607e-05 4.9516002e-05]]
2
[[5.0205832e-05 4.6248995e-05 4.9186088e-05]]
2
[[5.0273436e-05 4.5745994e-05 4.8864789e-05]]
2
[[5.0334311e-05 4.5293065e-05 4.8557504e-05]]
2
[[5.0389124e-05 4.4885226e-05 4.8268768e-05]]
0
[[4.9698567e-05 4.4517987e-05 4.8008777e-05]]
2
[[4.9076752e-05 4.4187305e-05 4.7761718e-05]]
2
[[4.8516842e-05 4.3889544e-05 4.7520694e-05]]
0
[[4.7299178e-05 4.3621425e-05 4.7303663e-05]]
2
[[4.6202731e-05 4.3379998e-05 4.7069658e-05]]
2
[[4.5215435e-05 4.3162603e-05 4.6820540e-05

[[2.2553937e-05 2.0337782e-05 2.3166071e-05]]
2
[[2.2146160e-05 2.0263156e-05 2.3074344e-05]]
2
[[2.1778977e-05 2.0195959e-05 2.2971422e-05]]
1
[[2.1448346e-05 2.0549942e-05 2.2878747e-05]]
2
[[2.1150630e-05 2.0868687e-05 2.2775122e-05]]
2
[[2.0882551e-05 2.1155700e-05 2.2661719e-05]]
2
[[2.0641161e-05 2.1414142e-05 2.2539603e-05]]
2
[[2.0423799e-05 2.1646856e-05 2.2409738e-05]]
2
[[2.0228075e-05 2.1856404e-05 2.2273001e-05]]
2
[[2.0051837e-05 2.2045091e-05 2.2130187e-05]]
0
[[2.0203255e-05 2.2214994e-05 2.2001590e-05]]
2
[[2.0339599e-05 2.2367984e-05 2.1869913e-05]]
1
[[2.0462370e-05 2.2219518e-05 2.1751344e-05]]
2
Buy: Rs.0.43
[[2.0572919e-05 2.2085831e-05 2.1633192e-05]]
1
[[2.0672464e-05 2.1682556e-05 2.1526801e-05]]
2
[[2.0762098e-05 2.1319427e-05 2.1414538e-05]]
2
[[2.0842810e-05 2.0992447e-05 2.1294454e-05]]
2
[[2.0915486e-05 2.0698018e-05 2.1167425e-05]]
2
[[2.0980928e-05 2.0432901e-05 2.1034244e-05]]
2
[[2.1039854e-05 2.0194175e-05 2.0895633e-05]]
2
[[2.1092914e-05 1.9979214e-

[[0.00262336 0.00237551 0.00239928]]
2
[[0.00264229 0.00243589 0.00239922]]
2
[[0.00265934 0.00249025 0.0024013 ]]
2
[[0.00267469 0.00253921 0.0024056 ]]
0
[[0.00264188 0.00258329 0.00240947]]
2
[[0.00261234 0.00262298 0.0024149 ]]
1
[[0.00258573 0.00262208 0.00241978]]
2
[[0.00256178 0.00262128 0.00242556]]
1
[[0.00254021 0.0025839  0.00243076]]
2
[[0.00252079 0.00255025 0.00248439]]
2
[[0.00250331 0.00251994 0.00253149]]
1
[[0.00248756 0.00246045 0.00257389]]
1
[[0.00247338 0.0024026  0.00261208]]
2
Sell: Rs.0.42 | Profit: Rs.0.05
[[0.00246061 0.00235051 0.0038149 ]]
2
[[0.00244911 0.00230361 0.00489454]]
2
[[0.00243876 0.00226138 0.00586227]]
2
[[0.00242944 0.00222335 0.00672837]]
2
[[0.00242105 0.00218911 0.00750216]]
0
[[0.00387871 0.00215827 0.00819893]]
2
[[0.00519127 0.00213051 0.0088189 ]]
2
[[0.00637316 0.00210551 0.00936917]]
0
[[0.00817014 0.002083   0.00986466]]
2
[[0.00978823 0.00206272 0.01030188]]
2
[[0.01124524 0.00204447 0.01068623]]
2
[[0.0125572  0.00202804 0.011032

[[0.07822101 0.07432848 0.08240168]]
2
[[0.0784381  0.07485887 0.08223908]]
2
[[0.07863358 0.07533645 0.08204064]]
2
[[0.0788096  0.07576649 0.08181001]]
0
[[0.0787495  0.07615372 0.08160234]]
2
[[0.07869538 0.0765024  0.08136365]]
1
[[0.07864664 0.07691447 0.08114871]]
2
[[0.07860276 0.07728553 0.08090372]]
1
[[0.07856325 0.07756665 0.08068312]]
2
[[0.07852767 0.07781978 0.080465  ]]
2
[[0.07849564 0.07804772 0.0802175 ]]
1
[[0.07846679 0.07802438 0.07999463]]
1
[[0.07844082 0.07775272 0.07979396]]
2
[[0.07841743 0.07750811 0.08037242]]
2
[[0.07839637 0.07728785 0.0814731 ]]
1
[[0.0783774  0.07710332 0.0824642 ]]
2
[[0.07836033 0.07693717 0.0833673 ]]
2
[[0.07834495 0.07678755 0.08412969]]
2
[[0.07833111 0.07665283 0.08476491]]
2
[[0.07831864 0.07653152 0.08528522]]
2
[[0.07830741 0.07642229 0.08570174]]
0
[[0.07891322 0.07632393 0.0860768 ]]
2
[[0.07945872 0.07623536 0.08636203]]
2
[[0.07994992 0.07615561 0.08656617]]
2
[[0.08039221 0.0760838  0.08669718]]
2
[[0.08079048 0.07601914 0

[[0.09306626 0.0912578  0.09846057]]
2
[[0.0930806  0.09156259 0.09820302]]
2
[[0.09309351 0.09183704 0.09791958]]
0
[[0.09309028 0.09208417 0.09766436]]
2
[[0.09308738 0.0923067  0.09738327]]
1
[[0.09308476 0.09253055 0.09713016]]
2
[[0.09308241 0.09273212 0.09685119]]
1
[[0.09308028 0.09283158 0.0966    ]]
2
[[0.09307837 0.09292115 0.09634928]]
2
[[0.09307665 0.09300179 0.09607282]]
1
[[0.0930751  0.09287802 0.09582388]]
1
[[0.09307371 0.09255816 0.09559973]]
2
[[0.09307245 0.09227014 0.09602458]]
2
[[0.09307132 0.0920108  0.09689017]]
1
[[0.0930703  0.09178121 0.0976696 ]]
2
[[0.09306938 0.09157449 0.09837263]]
2
[[0.09306855 0.09138834 0.09895524]]
2
[[0.09306781 0.09122073 0.09942912]]
2
[[0.09306714 0.0910698  0.09980484]]
2
[[0.09306654 0.0909339  0.10009197]]
2
[[0.09306599 0.09081152 0.10029918]]
2
[[0.0930655  0.09070133 0.1004343 ]]
2
[[0.09306506 0.09060211 0.10050444]]
2
[[0.09306467 0.09051276 0.10051601]]
2
[[0.09306431 0.09043231 0.10047482]]
2
[[0.09306399 0.09035987 0

[[0.0951133  0.09129983 0.10104895]]
0
[[0.09531471 0.09126253 0.10078421]]
2
[[0.09549607 0.09122893 0.10049856]]
1
[[0.09565938 0.09169635 0.10024135]]
2
[[0.09580643 0.09211724 0.09996269]]
1
[[0.09593885 0.0928262  0.09971177]]
2
[[0.09605808 0.09346459 0.09946246]]
2
[[0.09616544 0.09403943 0.09919123]]
1
[[0.09626211 0.09457947 0.098947  ]]
1
[[0.09634916 0.09499791 0.09872708]]
2
[[0.09642754 0.0953747  0.09908908]]
2
[[0.09649812 0.09571397 0.09984875]]
1
[[0.09656168 0.09591902 0.10053281]]
2
[[0.09661891 0.09610365 0.10114852]]
2
[[0.09667043 0.09626991 0.10165634]]
2
[[0.09671684 0.09641961 0.10206678]]
2
[[0.09675862 0.09655441 0.10238932]]
2
[[0.09679624 0.09667579 0.10263257]]
2
[[0.09683012 0.09678509 0.10280429]]
2
[[0.09686062 0.09688351 0.10291151]]
2
[[0.0968881  0.09697212 0.10296059]]
2
[[0.09691283 0.09705192 0.10295729]]
2
[[0.0969351  0.09712377 0.10290681]]
2
[[0.09695516 0.09718847 0.10281385]]
2
[[0.09697322 0.09724673 0.10268266]]
2
[[0.09698948 0.09729919 0

[[0.09799083 0.10275912 0.10033035]]
2
[[0.098022   0.10290789 0.10010068]]
2
[[0.09805007 0.10304184 0.09987357]]
0
[[0.09803625 0.10316246 0.09966905]]
2
[[0.09802382 0.10327107 0.09947042]]
2
[[0.09801262 0.10336888 0.0992797 ]]
1
[[0.09800253 0.10290284 0.09910797]]
2
Buy: Rs.0.51
[[0.09799345 0.10248319 0.09902871]]
1
[[0.09798528 0.1015704  0.09895735]]
1
[[0.09797791 0.10023163 0.0988931 ]]
2
[[0.09797128 0.09902613 0.09936354]]
2
[[0.09796531 0.09794064 0.10018931]]
1
[[0.09795994 0.09668073 0.10093287]]
2
[[0.09795509 0.09554625 0.10160202]]
2
[[0.09795073 0.0945247  0.10216107]]
2
[[0.09794681 0.09360484 0.10262075]]
2
[[0.09794328 0.09277656 0.10299075]]
2
[[0.09794009 0.09203073 0.10327981]]
2
[[0.09793723 0.09135915 0.10349587]]
2
[[0.09793465 0.09075443 0.10364608]]
2
[[0.09793232 0.0902099  0.10373692]]
2
[[0.09793023 0.08971959 0.10377426]]
2
[[0.09792835 0.08927808 0.10376339]]
2
[[0.09792665 0.08888052 0.10370911]]
2
[[0.09792512 0.08852255 0.10361574]]
2
[[0.09792374

[[0.09210209 0.08354431 0.09106895]]
2
[[0.09209158 0.08335762 0.09076214]]
2
[[0.09208212 0.08318953 0.09045712]]
2
[[0.0920736  0.08303817 0.0901563 ]]
0
[[0.09116524 0.08290188 0.08988543]]
2
[[0.09034731 0.08277915 0.08961271]]
2
[[0.0896108  0.08266865 0.08933387]]
1
[[0.08894761 0.08278592 0.08908279]]
2
[[0.08835044 0.08289152 0.08890557]]
1
[[0.08781271 0.08312452 0.08874598]]
2
[[0.08732852 0.08333433 0.08856319]]
1
[[0.08689253 0.08359369 0.08839859]]
2
[[0.08649994 0.08382723 0.08847585]]
1
[[0.08614644 0.08405734 0.08854541]]
2
[[0.08582813 0.08426454 0.08856905]]
2
[[0.0855415  0.08445111 0.08855132]]
2
[[0.08528341 0.0846191  0.08849632]]
2
[[0.08505101 0.08477038 0.08840778]]
2
[[0.08484174 0.08490659 0.08828907]]
2
[[0.08465331 0.08502924 0.08814321]]
2
[[0.08448364 0.08513969 0.08797298]]
2
[[0.08433086 0.08523914 0.08778084]]
2
[[0.08419328 0.08532869 0.08756906]]
2
[[0.0840694  0.08540933 0.08733966]]
2
[[0.08395786 0.08548193 0.08709449]]
2
[[0.08385742 0.08554731 0

### 4.0 Model Evaluation

In [ ]:
stock_name = input("Enter Stock_name, Model_name")
model_name = input()
model = load_model(model_name)
window_size = model.layers[0].input.shape.as_list()[1]
agent = Agent(window_size, True, model_name)
data = getStockDataVec(stock_name)
print(data)
l = len(data) - 1
batch_size = 32
state = getState(data, 0, window_size + 1)
print(state)
total_profit = 0
agent.inventory = []
print(l)
for t in range(l):
    action = agent.act(state)
    print(action)
    # sit
    next_state = getState(data, t + 1, window_size + 1)
    reward = 0
    if action == 1: # buy
        agent.inventory.append(data[t])
        print("Buy: " + formatPrice(data[t]))
    elif action == 2 and len(agent.inventory) > 0: # sell
        bought_price = agent.inventory.pop(0)
        reward = max(data[t] - bought_price, 0)
        total_profit += data[t] - bought_price
        print("Sell: " + formatPrice(data[t]) + " | Profit: " + formatPrice(data[t] - bought_price))
    done = True if t == l - 1 else False
    agent.memory.append((state, action, reward, next_state, done))
    state = next_state
    if done:
        print("--------------------------------")
        print(stock_name + " Total Profit: " + formatPrice(total_profit))
        print("--------------------------------")
        print ("Total profit is:",formatPrice(total_profit))